### ISSUE TITLE
The teacher information (exercise) is not being commited

### ISSUE THREAD

**Issue by huenu** [mumuki/mumuki-platform#100]
I wrote down some notes at the meta/teacher information field (exercise), and published the guide,  but I don't see it in [repo](https://github.com/Orga-UNQ/mumuki-guia-q3-rutinas)

**Comment by aguspina** [comment]
In which item? Exercise or guide?

**Comment by flbulgarelli** [comment]
@aguspina could you check both?

@huenu any ideas?

**Comment by aguspina** [comment]
I think its a bibliotheca bug

**Comment by flbulgarelli** [comment]
Lets assign high priority to it
