### ISSUE TITLE
Colours in Test Result: Red/Yellow/Green

### ISSUE THREAD

**Issue by asanzo** [mumuki/mumuki-platform#102]
Being able to differentiate among compilation error, exception in the program, and assertion failure.
Right now it's a mess to read and understand the result, and I think that's a prity good way to start changing it.

**Comment by flbulgarelli** [comment]
@faloi

**Comment by faloi** [comment]
+1

**Comment by faloi** [comment]
Bump! 

Gobstones is ready to be the first language to introduce this concept, we already can determine whether an error is a runtime error or not.

**Comment by flbulgarelli** [comment]
We should have three states instead of two. Perhaps `passed`, `failed` vs `pased`, `failed`, `errored`? (like travis).

Actually I reacently introduced the concept of `aborted`in mumukit for tests that exceed memory or time limits. Perhaps we need 4 states.

**Comment by flbulgarelli** [comment]
OK, now we support three error (red) types: `errored`, `aborted` and `failed`. And also a warning (yellow) state: `passed_with_warnings`. 

Also, now platform supports structured output for tests, so outputs should be clearer now - currently implemented for ruby, but haskell and js support is comming. 

Finally, we had added feedback - currently only supported for prolog - that translated common errors to human explanations. 

With that in mind, is still necessary to add more colors to distinguish errored, failed and aborted states? Is it not enough with showing different state titles to the user, @asanzo ?

**Comment by flbulgarelli** [comment]
Bump @asanzo @faloi

**Comment by faloi** [comment]
Let's consider this solved until proved otherwise
