### ISSUE TITLE
Inside a guide in Classroom, the guide's title in the upper bar isn't shown

### ISSUE THREAD

**Issue by gcrespi** [mumuki/mumuki-platform#103]
However there's a link to the guide in the gray space where it should be.
![captura de pantalla de 2016-06-11 18 50 48](https://cloud.githubusercontent.com/assets/10291211/15987642/9ecf03a8-3005-11e6-98f7-218e188c0c5b.png)

**Comment by faloi** [comment]
Possibly related to #90.
