### ISSUE TITLE
Manual correction

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-platform#117]
I'll drop here a few ideas about this topic, mainly thinking on improving both the teacher's experience when correcting and the student's experience when seeing the comments...

**Teacher**
- Notify teacher when a student sends a new solution of a commented exercise. That way the teacher doesn't have to visit every exercise again, she can just have a TODO list. See #6.
- Related to this, a comment could have a state of "pending/solved" that the student sees but only the teacher can modify. Somehow similar to #60.
- Improve navigation in exercise view, perhaps using shortcuts to move between exercises and solutions. It would also be nice to navigate between students - i.e. "let's see what Juanito did on this same exercise".

**Student**
- <del> Right now, the mechanism is pretty anti-democratic: the student can't reply in any way. I don't intend to implement a chat, but the ability to reply could be useful to clarify intentions. </del> (Done)
- <del>Increase comments affordance in Atheneum. Following with my idea of comments "with states", we can think of something like "goals" per exercise, that exist until the teacher marks them as solved. To enforce that idea, we should include a "Revision pending" state to an exercise, that replaces the "Success" status whenever an exercise has pending comments-goals.</del> (Done)

**Notifications**
- Both students and teachers could receive an email when something happens.

**Comment by flbulgarelli** [comment]
Related to https://github.com/mumuki/mumuki-atheneum/issues/599

**Comment by flbulgarelli** [comment]
Related to #235

**Comment by flbulgarelli** [comment]
> Related to this, a comment could have a state of "pending/solved" that the student sees but only the teacher can modify. Somehow similar to #60.

This is the most important aspect of this issue. We should address it. 

> Improve navigation in exercise view, perhaps using shortcuts to move between exercises and solutions. It would also be nice to navigate between students - i.e. "let's see what Juanito did on this same exercise".

@fedescarpa this is already working, isn't?
