### ISSUE TITLE
Add more feedback to Classroom subscription

### ISSUE THREAD

**Issue by mmatos** [mumuki/mumuki-platform#12]
It would be good to give a little more info to a student after they subscribe to a course to ensure they understand not only that it worked but what are the next steps.

I'm thinking they could receive an email after subscription (so they can go look for it later if they want) that says that the subscription to <name of the course> was successful, and from now on all submissions made in <domain>.mumuki.io would be visible to the teachers of that course.

I think that might help avoid missunderstandings of what to expect of the classroom and where to exercise.

**Comment by faloi** [comment]
The registration view now redirects to the lab after success.
