### ISSUE TITLE
Distinguish between My Courses and Other Courses

### ISSUE THREAD

**Issue by fdodino** [mumuki/mumuki-platform#120]
It would be nice to have 2 tabs in Courses View:
http://xxxxx.classroom.mumuki.io/#/courses
1) My Courses Tab , where you see related courses (based on teacher-course relation)
2) Other Courses Tab (non-related courses)

**Comment by flbulgarelli** [comment]
Now that we have different roles - teachers, headmasters and janitors - this should not be an issue anymore, since teachers only see courses that are actually related to them.
