### ISSUE TITLE
"Complements" category missing on guides view

### ISSUE THREAD

**Issue by JessSaavedra** [mumuki/mumuki-platform#122]
A complement that was showing a couple days ago is no longer showing

**Comment by flbulgarelli** [comment]
See http://pdep-utn.classroom.mumuki.io/#/courses/martes-manana/guides/pdep-utn/mumuki-TP-logico-entrega2-pulpFiction

It is there, but it is not shown in the guide's list

**Comment by aguspina** [comment]
Fixed in https://github.com/mumuki/mumuki-classroom/commit/5c9e2d2dffe313c5385897ae37c0b6d4ade7b1d8
