### ISSUE TITLE
Change subscription url to something without the "classroom" token?

### ISSUE THREAD

**Issue by matifreyre** [mumuki/mumuki-platform#13]
Not sure if this is possible...
Being a url for _students_, it would be nice to give them a _organization.mumuki.io/whatever_ address instead of a _organization.classroom.mumuki.io/whatever_ for the subscription to a given course.

**Comment by flbulgarelli** [comment]
Why?

**Comment by flbulgarelli** [comment]
I mean, why it would be nice to hide the classroom part? Because of security?

**Comment by matifreyre** [comment]
I see it more consistent in terms of the role you have:
- When you access as a student, you do it via _organization.mumuki.io_.
- When you access as a teacher, you do it via *
  organization.classroom.mumuki.io*.
  So when you enrole yourself in a course, your role is that of a student.

**Comment by flbulgarelli** [comment]
This is currently not possible with the current architecture. Closing this by now.
