### ISSUE TITLE
Manual evaluation still runs tests

### ISSUE THREAD

**Issue by asanzo** [mumuki/mumuki-platform#134]
This guide:

[http://pdep-utn.mumuki.io/complements/22-tp-sueldo-de-pepe](http://pdep-utn.mumuki.io/complements/22-tp-sueldo-de-pepe)

Has "Manual" evaluation marked for both exercises, and still it runs the tests I had last written before switching to Manual.

**Comment by flbulgarelli** [comment]
It's true! It's a bug!

**Comment by flbulgarelli** [comment]
Oh, no, sorry, it was a different  thing: since the import was failing, and you did not save any change after the bug fix, the changes in evaluation flag have not being reflected. 

I just reimported the guide and everything worked :wink:
