### ISSUE TITLE
Send email to users without any activity

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-platform#135]
In order to promote users to start using the platforms, we should send an email - periodically or at least manually - to all users that have no submission and have being registered, say, more than one month ago.

**Comment by jvillarejo** [comment]
What are you using for this? 

I like this small option:
https://github.com/jmettraux/rufus-scheduler

If not you can use this fatty boy
https://github.com/resque/resque-scheduler

**Comment by flbulgarelli** [comment]
Actually we have not starting using it yet. There is an implementation by @iluetich but I had no time to configure mailing nor to schedule mailing. 

We should respawn this issue

**Comment by flbulgarelli** [comment]
Ok, by now I went to a less scalable but quicker solution: I just added some filters to the admin user interface for getting users without recent activity. Then you can export that list as CSV from ActiveAdmin and import in Mailchimp or any service like that.
