### ISSUE TITLE
Add link from editor to expectations syntax 

### ISSUE THREAD

**Issue by PalumboN** [mumuki/mumuki-platform#14]
I'm making a new guide and I don't remember how declare an expectations. And I'm not finding its documentation :disappointed: 

Meybe a link or something with options, like a drop down, would be nice.

I see an option for advanced expectations, but I don't know what _subject_, _verb_ and _object_ mean.

**Comment by flbulgarelli** [comment]
See https://github.com/mumuki/mumuki.github.io/blob/old-master/_posts/2015-06-16-el-lenguaje-de-expectativas.markdown
