### ISSUE TITLE
Inconsistencia entre informacion de trabajos hechos

### ISSUE THREAD

**Issue by lhazuca** [mumuki/mumuki-platform#144]
En una pantalla se muestran que realizó una cantidad de ejercicios distinto a la que figura en la siguiente pantalla de un alumno.
Es el único alumno que pude encontrar con este error y ocurre únicamente en una guía.
El alumno realizó mas ejercicios y la información se siguió actualizando de forma inconsistente.

**Comment by faloi** [comment]
Cierro esto hasta que podamos encontrar un patrón.
