### ISSUE TITLE
Add Authoring tab to guide 

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-platform#145]
It should feature:
- Authors: a short text input - txt, not markdown
- Contributors: a long text input - txt, not markdown
- A disclaimer about the license and a link to it.

**Comment by flbulgarelli** [comment]
Also, the authors text box should be mandatory, right? @faloi

**Comment by faloi** [comment]
Yep. I don't like the "Legal" name, I'd name it "Authors" or "License".

**Comment by flbulgarelli** [comment]
@faloi ok

**Comment by flbulgarelli** [comment]
@faloi what about **attribution** instead of **authoring**? Attribution is more generic and covers authoring and contributing.

**Comment by faloi** [comment]
Errr, could be, I'm not familiar with the term so I can't say much.

PS: the editor deserves a Spanish version...
