### ISSUE TITLE
Add a mark to exercises with comments

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-platform#149]
Related to #117 

In exercises view, I imagine something like this:

![image](https://cloud.githubusercontent.com/assets/1585835/18234735/74bacabc-72e4-11e6-8861-f8ff9a4aef0a.png)

There, _1. Los números_ exercise has unresolved comments and _4. Las Funciones_ has solutions that have been sent after the last **negative** comment (probably not the best icon, I know).

**Comment by faloi** [comment]
@fedescarpa any updates on this one?

**Comment by fedescarpa** [comment]
Today I will send a PR with this feature and migration
