### ISSUE TITLE
Solutions submitted are not fully visible sometimes

### ISSUE THREAD

**Issue by mmatos** [mumuki/mumuki-platform#15]
I came accross some solutions in the classroom that at first I thought were incomplete but were actually not being displayed correctly.

See this one as an example, the solution #27
http://pdep-utn.classroom.mumuki.io/#/pdep-utn/2016-tar-mi/mumuki-guia-funcional-practica-valores-y-funciones/auth0%7C56f6a79f9a7df0726f99e57e/12

It looks like it's only 
`esBisiesto n1 = (esMultiploDe n1 4) && not(esMultiploDe n1 100)`

but if you double click to select the whole thing and copy it somewhere else it actually says
`esBisiesto n1 = (esMultiploDe n1 4) && not(esMultiploDe n1 100) ||(esMultiploDe n1 400)`

I was really confused at first cause all tests were passing, even the one that verified that missing condition.

**Comment by flbulgarelli** [comment]
Fixed. 

@mmatos please check now
