### ISSUE TITLE
"Course doesn't exist" error when trying to add teacher

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-platform#152]
![image](https://cloud.githubusercontent.com/assets/1585835/18256554/34632cee-738d-11e6-8790-b993f6e9a09b.png)

**Comment by faloi** [comment]
For now, I've added him via Auth0.

**Comment by flbulgarelli** [comment]
Is this still happening?

**Comment by flbulgarelli** [comment]
This issue even worse now - @fdodino has reported that a `Sinatra::NotFound` error is being raised. 

![unnamed](https://cloud.githubusercontent.com/assets/677436/22534725/ea56e678-e8d4-11e6-92c8-f25e8bbdcc61.png)

**Comment by aguspina** [comment]
Closed via https://github.com/mumuki/mumuki-classroom/commits/70e86bfffd8c6c4b709ef84bff26f6fb7c0ffec9

**Comment by flbulgarelli** [comment]
> Closed via https://github.com/mumuki/mumuki-classroom/commits/70e86bfffd8c6c4b709ef84bff26f6fb7c0ffec9

This commit does not exist :open_mouth:
