### ISSUE TITLE
Document inspection syntax and add a link to it from the exercise's crud

### ISSUE THREAD

**Issue by mmatos** [mumuki/mumuki-platform#153]
If you've never seen the source code for an exercise there's no way to know what kind of input would be expected in the Objectives tab of the UI editor.

If the Inspection field values are limited, a dropdown would be great to have.

**Comment by flbulgarelli** [comment]
Actually it is a bit more complex than that, since although inspection names are enumerable, inspections are expressions that may take parameters and be negated. 

Moreover, the actual available inspections may vary from language to language.

**Comment by flbulgarelli** [comment]
We could have a link to a documentation of the expressions, though

**Comment by flbulgarelli** [comment]
Related to #32

**Comment by flbulgarelli** [comment]
@mmatos  Please check this http://mumuki.org/expectativas/plataform/2015/06/16/el-lenguaje-de-expectativas.html

**Comment by mmatos** [comment]
I just read the post, it's a good referece material, linking from the exercice editor should be enough for a newbie. Thanks!
