### ISSUE TITLE
Export course data to JSON

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-platform#153]
As requested by @benotti, this would be useful for teachers that are doing some kind of research with students' data.

**Comment by flbulgarelli** [comment]
@faloi agreee, but don't you think we must address #139 first? 

It is important that only those student who have accepted the terms and conditions are displayed there.

**Comment by faloi** [comment]
Agree, but in her case that agreement was made outside of Mumuki - and she really needs the export functionality.

**Comment by flbulgarelli** [comment]
Ok, makes sense. In that case, my only concern is that the export functionality has some kind of disclaimer when you export all the students and not only those who have checked it. Something like "Warning: this export may contain sensitive data. You should not use or publish it without explicit authorization". 

@faloi side note: may the anonimization process be added here as an extra option? What do you think?

**Comment by faloi** [comment]
Ok, for now I'd just add the disclaimer, we can do better later.

I like the possibility of anonimizing the output, but I think it should be
addressed separately.

**Comment by flbulgarelli** [comment]
:+1:
