### ISSUE TITLE
Show the actual result of a past submission

### ISSUE THREAD

**Issue by mmatos** [mumuki/mumuki-platform#154]
When browsing past submissions for an exercise you see the code for that submission, but the result shown is not always the one corresponding to that submission.

If you open the submission in a new tab it behaves as expected and shows the result for that submission, but if you open it in the same tab it goes crazy, shows different things at first and then stabilizes on a result that may not be the one for that submission.

**Comment by flbulgarelli** [comment]
This will not be an issue anymore after merging of #162
