### ISSUE TITLE
Display exercise solving velocity

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-platform#154]
Moved from https://github.com/mumuki/mumuki-atheneum/issues/491

@asanzo said:

> If we could measure how long did it take to solve an exercise (or at least how much did it take between two sumbissions) that could give us interesting usage data.
> Actually, I thought this as a consequence of having certain doubts about if the pupils really read the purely theoretical exercises (with no coding needed).
> 
> Just an idea, not important.

**Comment by flbulgarelli** [comment]
@faloi this can be easily accomplish by displaying the difference between first and last solution. However, do you think it is helpful? Is it something we want to actually show?

**Comment by faloi** [comment]
I can't decide whether is useful or not, but seems a bit difficult to implement: imagine the student leaves the computer after the first submission and returns a week later, what shall we display? A week? The sum of time between submissions of the same day?

To much to think for a feature I'm not sure we need. :stuck_out_tongue:

**Comment by flbulgarelli** [comment]
Ok, can we close it then @faloi ?

**Comment by faloi** [comment]
Go ahead.
