### ISSUE TITLE
Add a validation for playground layout

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-platform#155]
See https://github.com/mumuki/mumuki-atheneum/commit/3bd5b485c9b841cad0053e521e11c015c681c5b7#commitcomment-18921495

**Comment by flbulgarelli** [comment]
Also,  when exercise is a reading, only `editor_bottom` should be allowed. In fact, there should be no button to change the layout.

**Comment by flbulgarelli** [comment]
@fedescarpa this issue has been already solve,  hasn't it?

**Comment by fedescarpa** [comment]
fixes in mumuki/mumuki-bibliotheca#71
