### ISSUE TITLE
Exercise deletion from UI doesn't work

### ISSUE THREAD

**Issue by mmatos** [mumuki/mumuki-platform#155]
I tried to delete an old exercise I created using the UI. After clicking on the trash icon first it prompts if your sure (once of firefox, it prompted a lot of times on chrome), after accepting the prompt it redirects unexpectedly to http://mumuki.io/es/exercises with the text "Exercise was successfully destroyed. " on the top, however I went back to my exercises and it was not deleted.

I tried this with an exercise that had 2 submissions, one was mine, the other wasn't, maybe that's related.

**Comment by flbulgarelli** [comment]
Related to #92
