### ISSUE TITLE
Support for different types of feedback

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-platform#156]
Right now, the feedback of a submission is assumed to be an html div with inline styles because the [Gobstones runner](https://github.com/uqbar-project/mumuki-gobstones-server) is the only one that uses it.

Each runner should be able to specify the type of its feedback, choosing between _plain_ (default) / _markdown_ / _html_, and the platform should render it accordingly. To accomplish this, the feedback should be turned into a structure that contains a type and a content (now it's just an string).

**Comment by flbulgarelli** [comment]
This was resolved with PR #169

**Comment by flbulgarelli** [comment]
Now it supports plain, html and markdown
