### ISSUE TITLE
Disable users

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-platform#160]
A teacher should be able to disable a user: tell that she is no more part of the course. 

This does not mean deleting her, but just disabling and showing when that happen. This should be done from the students view.

**Comment by faloi** [comment]
Which is the use case for this?

**Comment by flbulgarelli** [comment]
There are some private clients that require it.

**Comment by faloi** [comment]
Ok, I imagine then that those students can **potentially** be re-enabled (when they pay, for instance). Got it.
