### ISSUE TITLE
Use atheneum breadcrumbs style

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-platform#162]
Because it is not obvious that it is a breadcrumb

**Comment by aguspina** [comment]
<img width="1437" alt="screen shot 2016-09-09 at 4 26 35 pm" src="https://cloud.githubusercontent.com/assets/4105740/18400015/655b5ec8-76aa-11e6-9b7b-e623e699c365.png">

Something like this

**Comment by flbulgarelli** [comment]
If possible, it would be nice to use the styles extracted of atheneum by @fedescarpa 

https://github.com/mumuki/mumuki-styles

**Comment by aguspina** [comment]
Also, the `guides` breadcrumb should be renamed to `course-name`

**Comment by aguspina** [comment]
Closed via https://github.com/mumuki/mumuki-classroom/commit/7678a71935e27d9121fb00314c6109d885a15091
