### ISSUE TITLE
Add tooltips for progress ratios in course view

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-platform#163]
It should say something like 

> resolvió adecuademente X ejercicios, e intentó resolver Y

@faloi please comment

**Comment by aguspina** [comment]
<img width="1440" alt="screen shot 2016-09-09 at 4 42 19 pm" src="https://cloud.githubusercontent.com/assets/4105740/18400479/7a870264-76ac-11e6-8b7e-150603fbf761.png">

**Comment by faloi** [comment]
What's missing here is the total amount of exercises of the guide, that should be right below the guide name as it was in the original prototype. With that solved, I would copy the scheme present in the students' view: amount of green, yellow and red exercises.

**Comment by faloi** [comment]
Relying on a tooltip to explain our UI seems like a really bad idea, let's try instead to make it self-explanatory! :wink: 

And being consistent about how we display progress across the site seems like a good start to me...

**Comment by flbulgarelli** [comment]
> What's missing here is the total amount of exercises of the guide, that should be right below the guide name as it was in the original prototype. 

Ok. Please submit a new issue for that

> With that solved, I would copy the scheme present in the students' view: amount of green, yellow and red exercises.

I disagree. This view as already a lot of data. Adding more fields and components will make it even more complex. BUT that three numbers may be shown in the student detail view when you click on the student

**Comment by flbulgarelli** [comment]
> Relying on a tooltip to explain our UI seems like a really bad idea, let's try instead to make it self-explanatory! :wink:

I partially disagree. It is a good practice to minimize the level of dependence on tooltips, but you can't avoid them. Check for examples this Githubs UI, it has lots of tooltips. 

I am not saying that we should rely on tooltips, but it is certainly a good practice for _web_ design having them when possible.

**Comment by faloi** [comment]
Could be, but I don't think the current approach is useful, so I wanna focus on improving it rather than adding tootltips to explain it.

Do you really think this is too much information?
![image](https://cloud.githubusercontent.com/assets/1585835/18401364/93f71a28-76b0-11e6-881b-b691af06340c.png)

**Comment by aguspina** [comment]
@faloi we talk about it and we decide your approach is okay, but we need to add a tooltip for each status.
