### ISSUE TITLE
Consistent Open In Atheneum icon

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-platform#168]
_Open in atheneum_ links are too big and not consistently rendered regarding position and size in guide progress view and detail. 

We should use [this icon](http://fontawesome.io/icon/external-link/), render it always next to exercise/guide name, and open in a new tab.    

It should have a tooltip

**Comment by faloi** [comment]
Totally agree, I imagined it that way when I proposed the feature. :wink:
