### ISSUE TITLE
List of exercises with problems and no comments

### ISSUE THREAD

**Issue by estefaniamiguel** [mumuki/mumuki-platform#169]
I want to see a list of exercises with problems so I can go and add comments on them.
Every week I log to the classroom and go to every guide, to every student and see if there are any exercises that have a x or a ! and not a checkmark. If there are any, I send a comment to the student. Sometimes I enter exercises that already have a comment, so I waste time. A pain.

I want, as there are Guides - Students on a course, a new tab with a name like Revision or Exercises with problems.

That tab will have a list with all the exercises that have a x or a ! and not a checkmark. That list can be ordered by newest or by oldest (so you can correct those that couldn't be solved long time ago).

Once you click on the exercise, you go to the view of all the solutions sent : 
[https://postimg.org/image/iklu1kkr9/](url)
And everything goes as expected (you can comment, see older code, etc)

**Comment by estefaniamiguel** [comment]
I add another thing: maybe I can filter between x, ! and checkpoint.
Also we can go pro and filter by exercise or guide or student.

**Comment by faloi** [comment]
I like your idea, but I don't agree with your definition of "with problems". I send comments _mostly_ on green solutions, and following that idea I would like to see new solutions of exercises I commented.

Could work with the filter, so each teacher (or course) decides which solutions have priority.

**Comment by flbulgarelli** [comment]
Related to #235
