### ISSUE TITLE
No encuentro los ejercicios de una guía específica

### ISSUE THREAD

**Issue by Laucha1337** [mumuki/mumuki-platform#170]
Soy un alumno de paradigmas que está usando la página y al ingresar en una guía de ejercicios, no es intuitivo donde buscar la lista de ejercicios que comprenden la guía. Tocando los encontré en "Tus progresos" pero no pensaba que iban a estar ahí.

Mi sugerencia es que en ves de "Tus progresos" capaz pueda decir "Ejercicios de la guía" o algo por el estilo, ya que también van a aparecer los que aprobaste, los que no y los que no hiciste, a la par de ser más fácil darse cuenta. Saludos! muy buena la página

**Comment by PalumboN** [comment]
Muchas gracias por el feedback y las sugerencias! Las tendremos en cuenta. Saludos!

**Comment by flbulgarelli** [comment]
Buen punto. Subiendo prioridad

**Comment by flbulgarelli** [comment]
También se debería actualizar el ícono de forma acorde
