### ISSUE TITLE
Use icons instead of just colors for comment types

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-platform#174]
Currently the teacher selects a color for her comment. However, this is inconsistent with the rest of the platform. We should use ticks, warnings, etc form font awesome instead.

**Comment by faloi** [comment]
Agree. Moreover, current approach isn't color-blind friendly.

**Comment by flbulgarelli** [comment]
After the introduction of messages in classroom, comment and comment types have been removed.
