### ISSUE TITLE
Don't show progress items with 0's

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-platform#177]
Currently the guide progress view shows the progress of each student as a _semaphore_. However `0`s don't add any information. We should remove them.

**Comment by flbulgarelli** [comment]
@faloi

**Comment by faloi** [comment]
Removing them doesn't look so well, but disabling them seems better:

![image](https://cloud.githubusercontent.com/assets/1585835/18693400/dd7143ac-7f77-11e6-8e36-40508513c8d6.png)
