### ISSUE TITLE
Navigation through submissions of same guide

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-platform#18]
<a href="https://github.com/flbulgarelli"><img src="https://avatars.githubusercontent.com/u/677436?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [flbulgarelli](https://github.com/flbulgarelli)**
_Monday Feb 22, 2016 at 21:49 GMT_
_Originally opened as https://github.com/mumuki/mumuki-classroom/issues/3_

---

It is particularly useful when correcting exams

**Comment by faloi** [comment]
<a href="https://github.com/faloi"><img src="https://avatars.githubusercontent.com/u/1585835?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [faloi](https://github.com/faloi)**
_Tuesday Mar 22, 2016 at 13:07 GMT_

---

You mean through exercises, per student, right?

**Comment by faloi** [comment]
<a href="https://github.com/flbulgarelli"><img src="https://avatars.githubusercontent.com/u/677436?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [flbulgarelli](https://github.com/flbulgarelli)**
_Tuesday Mar 22, 2016 at 14:22 GMT_

---

right

**Comment by flbulgarelli** [comment]
Done
