### ISSUE TITLE
Error when I log in on a specific guide

### ISSUE THREAD

**Issue by tsandler** [mumuki/mumuki-platform#193]
When I go to the guide of chocobos without log in I can do it successfully, but when I enter my github username I get this error:

![error mumuki](https://cloud.githubusercontent.com/assets/7097531/8085184/324cb660-0f65-11e5-9417-3444206f26b9.jpg)

**Comment by flbulgarelli** [comment]
Fixed in #190. Is going to be deployed on production soon

**Comment by flbulgarelli** [comment]
@tsandler A workaround is to go to /guides/27/exercises path, fix broken exercises, and then go back to /guides/27

**Comment by flbulgarelli** [comment]
Deployed
