### ISSUE TITLE
Gobstones Runner: Add Initial Board to Test Result even when solution passes

### ISSUE THREAD

**Issue by asanzo** [mumuki/mumuki-platform#194]
When Programming in Gobstones IDE, it's very common to compare Initial Board with Result Board in order to understand why the error happened, or if the program did as expected. It'd be great to have both boards.

**Comment by flbulgarelli** [comment]
Hi!

When test fail, you get actually the initial board, expected final and actual final board, please  check that. 

But when test passes, you actually get only the final board. I agree that is not a good idea.

**Comment by flbulgarelli** [comment]
Related to uqbar-project/stones-spec#5

**Comment by flbulgarelli** [comment]
@faloi, please comment

**Comment by faloi** [comment]
I didn't create the issue, but we were talking about letting the teacher decide what to display in each exercise, with possible options: nothing, final board, initial and final board. 

Perhaps initial and final board could be the default.

**Comment by flbulgarelli** [comment]
:+1:

**Comment by faloi** [comment]
Moving this to https://github.com/uqbar-project/stones-spec/issues/17
