### ISSUE TITLE
Transferring a student modifies her registration time

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-platform#195]
The registration time is set to the time she was transferred. I believe it shouldn't be modified.

**Comment by flbulgarelli** [comment]
This may be a SEVERE issue. Are we not showing the original date or loosing it from the DB? @faloi 

If it is just an UI issue, we should address when possible. But if it a data issue, we must fix it urgently.

**Comment by faloi** [comment]
Looking at `students_2016_4b_grupo_1` collection on Mongo, `created_at` field is ok, but the JSON at `/courses/2016-4b-grupo-1/students` is not.

**Comment by faloi** [comment]
Closing, transfer is no longer available.
