### ISSUE TITLE
Guide types: learning vs practicing guides

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-platform#196]
Currently we have developed two types of guides: 

* **"learning campaigns"**, that cover very few tools or elements from theory, have no domain, and may contain explanations. Those guides are usually named in spanish as "mumuki-funcional-guia-3-haskell-lambdas"
* **"challenge campaigns"** , which cover more elements, have a richer domain, and contain no explanations. Those guides are usually named in spanish as "mumuki-funcional-tp-chocobos"

It would be nice to let the platform know about that, and have a different visual presentation, in order to recognize them easily

**Comment by flbulgarelli** [comment]
@faloi @PalumboN @aguspina @mmatos @asanzo I would like to hear your opinions here

**Comment by faloi** [comment]
+1 to this.

I think we should provide at least a challenge guide for each learning guide, so the student can optionally practise what she/he has just learned. 

Another difference I see is subject-specific guides (e. g. conditional repetition on Gobstones or higher order functions on Haskell) VS what you described there, that could cover many aspects of the paradigm.

**Comment by faloi** [comment]
Moving this to https://github.com/uqbar-project/stones-spec/issues/17
