### ISSUE TITLE
Default course for students that haven't registered

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-platform#20]
<a href="https://github.com/faloi"><img src="https://avatars.githubusercontent.com/u/1585835?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [faloi](https://github.com/faloi)**
_Tuesday Mar 01, 2016 at 20:24 GMT_
_Originally opened as https://github.com/mumuki/mumuki-classroom/issues/5_

---

**Comment by flbulgarelli** [comment]
@faloi since now all solutions from central or from a wrong organization are stored in the failed submissions collection, they can be easily resubmitted, does this still have sense?

**Comment by faloi** [comment]
Nope and what's more, now organizations are private so this case is nearly impossible to happen.
