### ISSUE TITLE
Redirect to last guide

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-platform#200]
When a logged user visits home again from a different site, he/she should be redirected to the last guide. 

That way you keep context and it is not necessary to look for the guide again. 

This should not affect flow when you visit it from within mumuki. 

A message saying "welcome back, we have recovered you workspace for you" or something like that could also be a good idea.

**Comment by flbulgarelli** [comment]
Any comments? @faloi @jvillarejo @PalumboN @aguspina ?

**Comment by faloi** [comment]
I like this but redirecting the user sounds a bit agressive to me. Also I'm thinking that the student could be working on different guides at the same time.

Perhaps we can do something like Netflix's "Continue watching" feature:

![image](https://cloud.githubusercontent.com/assets/1585835/8134346/cc9563ac-1104-11e5-8f47-6d478d5b2397.png)

**Comment by flbulgarelli** [comment]
Yes, that could work, show the last 4 or 5 guides or paths he or she has tried. 

But.... that means a redesign of the homepage - which is actually necessary, though. Why not going for the plain redirect now, and then implement this feature in the future?

**Comment by flbulgarelli** [comment]
And I don't think there are too many users doing two guides of different paths at the same time now, do you?

**Comment by faloi** [comment]
Agree
