### ISSUE TITLE
Support choices exercise in bibliotheca

### ISSUE THREAD

**Issue by aguspina** [mumuki/mumuki-platform#201]

**Comment by flbulgarelli** [comment]
What is missing about this? Atheneum import integration, right?

**Comment by flbulgarelli** [comment]
@aguspina but was atheneum integration done? If not, we can't close this issue yet

**Comment by aguspina** [comment]
I'm on it! I'm creating a new issue because this issue vas specific for
bibliotheca

**Comment by flbulgarelli** [comment]
:kissing_heart:
