### ISSUE TITLE
Haskell extras.hs concatenation bug

### ISSUE THREAD

**Issue by asanzo** [mumuki/mumuki-platform#208]
Hi!
We've been having trouble when trying to run exercises that have an extras.hs in the guide and an extras.hs in the exercise. 
Run output is something like "unexpected '=' in output "

The problem arises from this line: https://github.com/mumuki/mumuki-platform/blob/master/app/models/exercise.rb#L64

It adds spaces on both sides of the "/n" and if the second source file has a function at the beggining, then this adds a space to the begginging of the line, and Haskell doesn't like this.

@PalumboN

**Comment by flbulgarelli** [comment]
Nice catch
