### ISSUE TITLE
Rename this repository to mumuki-platform

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-platform#211]
Since we are opening github issues again for editor and classroom, and there are sometimes issues that simply affect all the platform, why not just renaming this repository and accepting generic issues, as a single entry point for bug reporters?

**Comment by faloi** [comment]
I agree. Perhaps we should also explain it in the README and CONTRIBUTING guidelines of the other repos.

**Comment by flbulgarelli** [comment]
@faloi would you like to take this issue?
