### ISSUE TITLE
Allow runners to also execute arbitrary code

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-platform#211]
This would allow the implementation of Repls into the platforms.

**Comment by faloi** [comment]
The extra code should be available on each exercise's REPL

**Comment by flbulgarelli** [comment]
We could use this https://github.com/chrisdone/jquery-console

**Comment by flbulgarelli** [comment]
Btw, should the repl be available to all exercises? Or should we add as a different type of exercise? Or should we support both use cases: repl's as a quick testing tool for users AND repl's as a new type of exercise?

**Comment by faloi** [comment]
I think both things could be useful. 

The first one could be something like RubyMonk, where you have to test a short expression and tests are run in place. 

The second one could be available for every exercise, sometimes is useful to run arbitrary code while programming (e.g. I usually drop a few expressions on **irb** while coding). This should be configurable for each language, it doesn't make sense for Gobstones for instance.

**Comment by flbulgarelli** [comment]
I think the second one is simpler. We could start there. 

However, we need to think how we should render it. Should it be above or under the editor? Or in another place?

**Comment by flbulgarelli** [comment]
Let's assume that we _can_ add this feature to the runners, and that we _want_ to just support it as quick interactive way for the user to play with her code before submitting it. Were could we place it?

Here there is an option - ignore colors, just focus on position:

![console_position](https://cloud.githubusercontent.com/assets/677436/8207704/a6a276de-14d9-11e5-8f9b-9096afbb80ac.png)

On the other hand, should it be always visible to languages that support it? Or hidden by default? How should the user activate it? Do we know about any other site that supports at the same time the following?

* an editor
* a repl
* a description

@faloi @mmatos

**Comment by faloi** [comment]
I like it, even the colors. I would add a caption "You can test your code
here before submission", though.

Visible by default seems good to me.

**Comment by aguspina** [comment]
Love this feautre

**Comment by flbulgarelli** [comment]
What about something like this?

![screenshot - 280815 - 17 02 08](https://cloud.githubusercontent.com/assets/677436/9556001/adfcfa6a-4da7-11e5-9504-8bb835c4348b.png)
![screenshot - 280815 - 17 03 06](https://cloud.githubusercontent.com/assets/677436/9556002/ae03758e-4da7-11e5-9eb4-050eddaec10c.png)

**Comment by aguspina** [comment]
Really like this

**Comment by flbulgarelli** [comment]
Perhaps we could customize tabs css to look smaller.

I don't really like the black console. What about using a white background with the Mumuki colors theme?

**Comment by faloi** [comment]
The tabbed version is nicer, but more hidden than the other one. Perhaps customizing the CSS and adding a representative icon to each tab could work.

Another thing that would be nice is to include a "wizard" like Google or Facebook do many times, telling the user about our new feature. Something like _"Hey, you can now execute any code here before you send the submission. Wanna try? Just drop a `2+2` in the console, and press Ctrl + Enter to see it in action"_
