### ISSUE TITLE
Can't access courses in classroom

### ISSUE THREAD

**Issue by matifreyre** [mumuki/mumuki-platform#218]
When clicking on any course, no matter if it's mine (e.g. 2016 - K2006) or not, no action is taken. I can see a progress bar get filled at the top of the page, but when it finishes it just disappears and nothing changes.

I imagine this may be related to #216.

**Comment by flbulgarelli** [comment]
> I imagine this may be related to #216.

It is! We are working on it

**Comment by flbulgarelli** [comment]
Solved. Please check now.

**Comment by matifreyre** [comment]
Not this one... I was able edit content, but courses are still the same, I can't access them.

**Comment by matifreyre** [comment]
Wait... incognito mode did the trick. I'll have to delete caché and that kind of stuff.
