### ISSUE TITLE
New Login Architecture

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-platform#219]
Extracted from an internal SAML-integration discussion email:

> En el proceso de integración con SAML nos dimos cuenta de algunas complejidades:
> 
> 1. Login centralizado: la integración con SAML planteada al día de hoy (https://github.com/mumuki/mumuki-laboratory/pull/725) permite autenticarse contra
SAML de a una aplicación por vez. Es decir, para entrar a cada aplicación de la plataforma debería presionar el botón login, redirigir al IDP y recién ahí estar logueado, en lugar de estar logueado directamente (SSO). No es algo terrible, pero sí perfectible. 
> 2. Relacionado con lo anterior, no estamos contemplando tampoco un Single Sign-Out
> 3. El callback de autenticación SAML debe ser idealmente contra un mismo dominio (por ejemplo auth.mumuki.io), o al menos un conjunto acotado (https:://laboratory.mumuki.io/auth, https:://classroom.mumuki.io/auth, etc). Ya concluimos que lo segundo es fácil de hacer: se trata de simplemente colocar una ruta en cada aplicación que redirija al dominio en el que estaba anteriormente, sacándolo de una cookie específica para esa aplicación. Sin embargo, esto implica no en todas las aplicaciones de mumuki una lógica muy similar y no contribuye (al menos, en apariencia) a resolver los problemas 1 y 2. 
> 4. Dos de las aplicaciones de la plataforma son Single Page Apps (escritas en Angular), clientes pesados que sólo consumen al servicio a través de APIs, y que al día de hoy resuelven el login en el cliente. Después de explorar opciones como saml2-js, concluimos que es mucho más simple y mantenible mover la lógica de login al servidor que realizarla en el cliente. 
> 5. Utilizar Auth0, Saml o cualquier otro proveedor debe ser un proceso simple y transparente, y tienen que funcionar en cada una de las 4 aplicaciones de la plataforma (Laboratory, Office, Bibliotheca y Classroom), por lo que es necesario incorporar toda la lógica en todas las aplicaciones. Si no tenemos cuidado, estoy puede terminar siendo difícil de mantener por lo que es necesario o bien unificar la arquitectura de login en todas ellas y extraer una biblioteca o bien delegarla en un servicio externo. 
> 6. Todas las aplicaciones soportan internacionalización, y es necesario asegurarse de que todas ellas se vean en el mismo idioma, pero hoy no existe un punto único de dónde consultar el idioma preferido del usuario. 
> 
> Por todo esto, tenemos que encarar en los próximos días un refactor a la arquitectura de login, el problema es que no terminamos de decidirnos por cuál es el camino más correcto. Hay tres opciones: 
> 
> 1. Unificar el login de las aplicaciones para que sea siempre resuelto en el servidor, utilizando la gema Omniauth y manejando la información de sesión en cookies. Además, extraer la lógica común (posibilidad de alternar proveedores, callbacks en un solo dominio, etc) a una biblioteca para no repetir lógica. 
>
> Esto implica generalizar y hacer pequeñas modificaciones en laboratory (que ya usa omniauth y ya tiene soporte para SAML), replicarlas en Office (que tiene la misma arquitectura que Laboratory) y reescribir el login de classroom y Bibliotheca para llevarlo al servidor. 
> 
> Si bien esto no resuelve los problemas 1 y 2, si se compartiera los secrets que se utilizan para encriptar las cookies entre los servidores (a través de un archivo de configuración) y se utilizaran cookies cross domain sería posible lograr SSO.
> 
> De todas formas, esto no da ninguna solución al problema 6 (¿o sí?).
> 
> 2.  Crear una quinta aplicación para que maneje el login, que actúe como adaptador entre la plataforma y Auth0/SAML o cualquier otro proveedor. Podría devolver ante un login un redirect a la aplicación original y manejar la información de autenticación a través de un bearer token (para las aplicaciones Single Page), un authorization code (para aplicaciones server side) y/o cookies cross-domain. El problema es que implica agregar un componente más a la arquitectura (lo cual preferiría evitar salvo que tengamos un buen motivo) y siento que estamos reinventando la rueda, dado que tanto Auth0 como SAML de una u otra forma son abstracciones que permiten autenticación interoperable. 
> 
> Además, otra contra que veo es que si bien podríamos usar un protocolo propio, habiendo ya otros existentes (CAS, OAuth2 (pese a que para ser justos sea principalmente un protocolo de autorización), SAML), parece un despropósito para un proyecto de código abierto. Por lo que habría que implementar probablemente alguno de esos estándares. 
> 
> 3. Llevar todo al servidor (como en la opción 1), pero que la autenticación sea siempre a través de SAML, y consumir Auth0 como si fuera un IDP Saml (lo cual según ésto y ésto parecería posible). La ventaja es que parece una solución simple y elegante, pero corremos el riesgo de dificultar integraciones con otros métodos de autenticación. Además de que implica realizar una apuesta fuerte por un protocolo que recién estamos conociendo. 
> 

Any thoughts? @fedescarpa @Charlyzzz @rodri042 @aguspina @dggluz

**Comment by flbulgarelli** [comment]
Related to https://github.com/mumuki/mumuki-laboratory/issues/734

**Comment by flbulgarelli** [comment]
Related to https://github.com/mumuki/mumuki-laboratory/issues/688. 

In addition to language preferences per organization, we should have a theme per organization - in office - and display them accordingly on the login page.

**Comment by afska** [comment]
> Unificar el login de las aplicaciones para que sea siempre resuelto en el servidor, utilizando la gema Omniauth y manejando la información de sesión en cookies. Además, extraer la lógica común (posibilidad de alternar proveedores, callbacks en un solo dominio, etc) a una biblioteca para no repetir lógica.

Me parece más limpia esta opción. No me convence que todo el login quede acoplado a SAML más allá de que sea un protocolo estándar **(3)**.

La ventaja de **(2)** es que -por ejemplo- si ese nuevo componente es un servidor de OAuth2 le facilitaría las cosas a terceros para hacer aplicaciones que se integren con la plataforma. Peeero es un SPOF gigante, hacerlo bien (seguro, rápido, etc) es complejo y no sé si queremos ir todavía en esta dirección.

> De todas formas, esto no da ninguna solución al problema 6 (¿o sí?).

¿Persistiendo esas preferencias como el idioma en la cookie no se solucionaría?

**Comment by dggluz** [comment]
Bueno, estuvimos charlando un poco el asunto con @fedescarpa y @aguspina y llegamos a un par de conclusiones:
1. Respecto de los puntos 1 y 2, podemos resolverlo compartiendo _cookies_, ya que todas las aplicaciones están bajo un mismo dominio (seteando el dominio de la cookie a `.dominio.com`). Acá tenemos dos opciones (y no definimos aún cuál preferimos):
        a. Compartir una _sesión_ entre todas las aplicaciones, y levantar un nuevo servicio que _mapee_ los _session tokens_ a `uid` (el único dato que tendría sentido compartir). Este servicio podría ser un _redis_, un _memcache_ o cualquier otro similar que pueda resolver muy rápidamente el _mapeo_.
        b. Guardar el `uid` directamente en las _cookies_.
2. Loguearse siempre consistentemente, sin importar la _estrategia_ (_SAML_, _auth0_, etc.): autenticar desde el servidor y que el mismo responda _directamente_ al cliente (que no haya un _middleware_ en el medio), ya que, por ejemplo, un _IdP SAML_ asume que va a poder utilizar cookies y enviar código HTML (incluyendo JavaScript) al cliente.
3. Usar los servicios de autenticación, justamente, para autenticar **y nada más** (los permisos manejarlos por otro lado).
4. Tener en cuenta que un _IdP SAML_ es _statefull_ (hay que _desloguear_ allí también).
5. No llegamos aún a la conclusión de si llevar todo el código de autenticación a un solo componente (_Office_ sería un buen candidato) o si compartir una gema con el código reutilizable y que cada aplicación autentique por su lado, pero sí descartamos usar _auth0_ como _IdP SAML_ (opción 3). Personalmente, me inclino por llevar todo a _Office_ (está escrito en Rails, al igual que Laboratory, entonces llevar el código de un lado a otro debería ser trivial).

Bueno, creo que eso es todo. Fede, Agus, si recuerdan algo más que esté olvidando, por favor coméntenlo.

**Comment by flbulgarelli** [comment]
> Me parece más limpia esta opción. No me convence que todo el login quede acoplado a SAML más allá de que sea un protocolo estándar (3).

Coincido

> La ventaja de (2) es que -por ejemplo- si ese nuevo componente es un servidor de OAuth2 le facilitaría las cosas a terceros para hacer aplicaciones que se integren con la plataforma. Peeero es un SPOF gigante, hacerlo bien (seguro, rápido, etc) es complejo y no sé si queremos ir todavía en esta dirección.

Coincido. En particular en lo relacionado al SPOF: cualquier caída o ralentización del servicio afecta a toda la plataforma. 

> Respecto de los puntos 1 y 2, podemos resolverlo compartiendo cookies, ya que todas las aplicaciones están bajo un mismo dominio (seteando el dominio de la cookie a .dominio.com).

Estoy de acuerdo. De hecho, ya estamos utilizando cookies _cross-domain_ para manejar el login a través de múltiples organizaciones en `laboratory`

> a. Compartir una sesión entre todas las aplicaciones, y levantar un nuevo servicio que mapee los session tokens a uid (el único dato que tendría sentido compartir). Este servicio podría ser un redis, un memcache o cualquier otro similar que pueda resolver muy rápidamente el mapeo.

Me parece complejo, nuevamente un único punto de falla, y no veo qué aporta esto a la solución. Salvo que haya algo que no esté viendo, no iría por este camino. 

> b. Guardar el uid directamente en las cookies.

Me parece correcto. Incluso se podría almacenar en la cookie las preferencias de idioma, como dijo @rodri042 antes. O bien, se podría incorporar al perfil del usuario, el cual, tras haber sido consumido de la cola de eventos, ya habrá sido persistido en la aplicación al momento del login. 

> Loguearse siempre consistentemente, sin importar la estrategia (SAML, auth0, etc.): autenticar desde el servidor y que el mismo responda directamente al cliente (que no haya un middleware en el medio), ya que, por ejemplo, un IdP SAML asume que va a poder utilizar cookies y enviar código HTML (incluyendo JavaScript) al cliente. 

:+1: 

> Usar los servicios de autenticación, justamente, para autenticar y nada más (los permisos manejarlos por otro lado).

:+1: 

>  Tener en cuenta que un IdP SAML es statefull (hay que desloguear allí también).

:+1: 

El deslogueo tambien debe incluir la destrucción de la cookie de sesión. 

> No llegamos aún a la conclusión de si llevar todo el código de autenticación a un solo componente (Office sería un buen candidato) o si compartir una gema con el código reutilizable y que cada aplicación autentique por su lado, 

Llevarlo a un sólo *servicio* llevaría  a la solución similar a la planteada antes _2. Crear una quinta aplicación para que maneje el login_, que tiene aparejado el problema de ser un SPOF, aumentar latencias, y incrementar el acoplamiento entre las aplicaciones existentes, reinventar la rueda, etc, sólo que no sería tan complejo porque no necesitaría una aplicación extra.  

Yo me inclino mucho más por llevarlo todo a una biblioteca reutilizable.  

> pero sí descartamos usar auth0 como IdP SAML (opción 3). 

:+1:

**Comment by flbulgarelli** [comment]
PD: Dado que todo parece inidicar que vamos a ir por una solución basada en cookies, leer https://github.com/blog/1466-yummy-cookies-across-domains

**Comment by flbulgarelli** [comment]
En resumen: 

1. cada app debe tener su propio login https://github.com/mumuki/mumukit-auth/issues/23
2. todas las apps deben loguearse con omniauth en el servidor, utilizando un proveedor seleccionable a por variable de entorno
    * laboratorio https://github.com/mumuki/mumuki-laboratory/pull/725 
    * secretaría https://github.com/mumuki/mumuki-office/issues/19
    * aula
    * biblioteca https://github.com/mumuki/mumuki-bibliotheca/issues/51
3. las sesiones deben manejarse usando cookies en todas las aplicaciones
4. <del>`mumukit-auth`</del> Una nueva gema `mumukit-login` (https://github.com/mumuki/mumukit-login) proveerá el módulo `Mumukit::Login` que evitará la lógica repetida
    * Selección del proveedor a través de variables de entorno
    * Personalizaciones de la UI

**Comment by flbulgarelli** [comment]
Done!
