### ISSUE TITLE
Error when selecting guide link on excercise http://es.mumuki.io/exercises/304

### ISSUE THREAD

**Issue by jvillarejo** [mumuki/mumuki-platform#221]
![mumuki guide bug](https://cloud.githubusercontent.com/assets/1713500/8176120/79e2f2d0-13cc-11e5-9728-85aa3a33ce19.gif)

**Comment by faloi** [comment]
This is fixed by now, perhaps you tried this during the db migration? @flbulgarelli should know

**Comment by flbulgarelli** [comment]
Seems legit
