### ISSUE TITLE
Reify failed examples and display them accordingly

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-platform#223]
The error output from most runners (except from Gobstones :smirk:) is very rough to a student: tempfile paths, test framework language, etc.

Runners should be able to return structured data instead of string, configurable on a per language basis. This data should be a JSON and could consist of:
- a `global_status`, with possible values `failed|passed`
- an array of `examples`, with:
  + a `title`, in sentence case
  + a `status`, with possible values `failed|passed`
  + an `output`, with the content-type defined for the language

<s>To make this change backward compatible, a language should be able to opt-in by setting a flag "Returns structured data?"</s>

**Comment by faloi** [comment]
Related to https://github.com/uqbar-project/stones-spec/issues/4 and https://github.com/uqbar-project/stones-spec/issues/5

**Comment by flbulgarelli** [comment]
Related to #102

**Comment by flbulgarelli** [comment]
That would also help in #52, since it would provide the platform with a metric of how much close a user is to finish the exercise

**Comment by flbulgarelli** [comment]
The rspec runner will be the reference implementation for this: https://github.com/mumuki/mumuki-rspec-server/tree/feature-structured-output

**Comment by flbulgarelli** [comment]
With this in mind, and since we want to preserve original unstructured behaviour by default, we will have to provide two types of json outputs:

## Unstructured

```json
{
  "exit":"passed/failed",
  "out":"....the test runner raw output ...." ,
  "feedback": "...the runner feedback....",
  "expectationResults": [
    {"expectation":{"binding":"..the binding...", "inspection": "...the inspection..."}, "result":true/false},
    ...
  ]
}
```
## Structured

```json
{
  "testResult": {
    "status":"passed/failed",
    "examples": [{"title":"the title", "status":"passed/failed", "result":"...the test result output...."}]
  },  
  "feedback": "...the runner feedback....",
  "expectationResults": [
    {"expectation":{"binding":"..the binding...", "inspection": "...the inspection..."}, "result":true/false},
    ...
  ]
} 
```

Platform will need to be modified to support a flag of *unstructured data*

**Comment by flbulgarelli** [comment]
@faloi please check my last comment

**Comment by faloi** [comment]
> @faloi please check my last comment

Looks great

**Comment by flbulgarelli** [comment]
Haskell implementation: mumuki/mumuki-hspec-server#8
