### ISSUE TITLE
Split events

### ISSUE THREAD

**Issue by aguspina** [mumuki/mumuki-platform#228]
Nowadays in the PermissionsDiff we calculate in Classroom we have many issues:

1. If someone register a teacher as a student in a course, this has no effect in classroom.
2. The event action is not idempotent.

We need to split the StudentChanged event into more events:
1. StudentCreated
2. StudentUpdated
3. StudentRegistered

**Comment by flbulgarelli** [comment]
The described semantics are tricky too, since it could lead to race conditions among multiple servers and process the update event before the create event. Won't fix.
