### ISSUE TITLE
Classroom won't let me into my course

### ISSUE THREAD

**Issue by asanzo** [mumuki/mumuki-platform#232]
When clicking in my course name, it does nothing. The console throws a "Forbidden 403" error.

![seleccion_092](https://cloud.githubusercontent.com/assets/5421992/22895842/a410feca-f1fc-11e6-8d47-fb34d0e19c7b.png)

I tried logging in with both my Gmail and Github accounts.

**Comment by aguspina** [comment]
Fixed
