### ISSUE TITLE
Classroom Logout

### ISSUE THREAD

**Issue by asanzo** [mumuki/mumuki-platform#233]
When clicking on my avatar nothing happens. I'd like to be able to logout.

![seleccion_093](https://cloud.githubusercontent.com/assets/5421992/22896155/c49f9e52-f1fd-11e6-8fda-8bc91e68797c.png)

Not that important, really, but it's a bit annoying to have to manually clean cookies. 

It isn't that necessary in the classroom, though.

**Comment by aguspina** [comment]
This bug was fixed via #https://github.com/mumuki/mumuki-classroom/commit/e30b5f55373a16e2288b71a33811780c899384ad but it isn't deployed yet.
