### ISSUE TITLE
Editor: popups an "this.test is undefined" and the guide cant be saved

### ISSUE THREAD

**Issue by huenu** [mumuki/mumuki-platform#234]
No matter the nature of the change (guide description, the tests of an exercise, etc), when i try to save the modifications, I obtain a pop-up with this message: "this.test is undefined"

**Comment by flbulgarelli** [comment]
@huenu could you please tell which guide are your trying to save?

**Comment by huenu** [comment]
It  happens at every guide of my book ( https://github.com/Orga-UNQ)

**Comment by fedescarpa** [comment]
¡Hola @huenu! Proba ahora y decinos si ya anda. A tus guías les faltaban tests y el mensaje de error era bastante feo. Ahora mejoré el mensaje para que diga qué guía o ejercicio falla y por qué.

Saludos
