### ISSUE TITLE
Raise Hand

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-platform#235]
Students need to be able to notify teachers when they cannot solve the exercise.

Otherwise, teacher must manually inspect each student progress, which is cumbersome.

**Comment by flbulgarelli** [comment]
Related to #60

**Comment by aguspina** [comment]
Resolved in https://github.com/mumuki/mumuki-laboratory/commits/e22c187c0644260526a983b6b4c4ea4382447107
