### ISSUE TITLE
Home page redesign

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-platform#237]
Now that we have improved the submissions page, the next UI problem is the homepage.

**Comment by flbulgarelli** [comment]
@jvillarejo @faloi I would like to hear opinions about this

![screenshot from 2015-06-24 20 49 20](https://cloud.githubusercontent.com/assets/677436/8344064/85790c96-1ab2-11e5-931b-a4fdca0f1606.png)

**Comment by faloi** [comment]
- I like the fact that the logo is more visible. We need to start spreading it everywhere if we want to create a brand sense.
- The links are not so visible, they looked better within the navbar.
- I miss the "Start practicing" button

**Comment by flbulgarelli** [comment]
@faloi OK, I added the start practicing button again. And image was shadowed in order to make links  more visible
