### ISSUE TITLE
Abrir links de los ejercicios en una pestaña nueva

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-platform#238]
Es usual que en un ejercicio se haga alguna referencia a algún recurso externo, como por ejemplo un link a Wikipedia. Hoy en día esos links se abren en la misma pestaña, pudiendo provocar que el estudiante pierda el trabajo que estaba siendo.

Sería interesante que todos los links que hay en los ejercicios se abrieran en una pestaña nueva por defecto.

**Comment by fedescarpa** [comment]
probablemente sea pisar un método en la clase content type... como ya está hecho el de [table](https://github.com/mumuki/mumukit-content-type/blob/master/lib/mumukit/content_type/markdown.rb#L11)
