### ISSUE TITLE
Inhabilitar el input del corolario para ejercicios de tipo Juego 

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-platform#240]
Porque ese tipo de ejercicio no tiene corolario, y es bastante confuso que te deje ingresarlo siendo que luego no aparecerá nunca.

**Comment by flbulgarelli** [comment]
Duplicated of https://github.com/mumuki/mumuki-platform/issues/137

**Comment by flbulgarelli** [comment]
Also, this issue has been already fixed and it's fix will be present on next version.
