### ISSUE TITLE
No aparece el código extra de la guía

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-platform#242]
Para reproducirlo, basta con entrar a http://bibliotheca.mumuki.io/#/guides/mumukiproject/mumuki-guia-ruby-objetos-y-mensajes y ver que no hay código extra, siendo que tanto [en la API](http://bibliotheca-api.mumuki.io/guides/mumukiproject/mumuki-guia-ruby-objetos-y-mensajes) como [en GitHub](https://github.com/MumukiProject/mumuki-guia-ruby-objetos-y-mensajes) sí lo tiene.

**Comment by flbulgarelli** [comment]
Por lo que veo, sí está, pero sólo aparece después de hacer click o scroll sobre el editor de código extra :open_mouth:

**Comment by flbulgarelli** [comment]
Fixed.
