### ISSUE TITLE
Improve path string rendering

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-platform#242]
![screenshot from 2015-06-30 21 03 17](https://cloud.githubusercontent.com/assets/1585835/8444792/9707e32a-1f6b-11e5-817d-d2a5f77f2694.png)

**Comment by flbulgarelli** [comment]
Sorry, I didn't get the issue. Why is it not working properly?

**Comment by faloi** [comment]
It's not a link, it says _gobstones/Fundamentos de la Programación_

**Comment by flbulgarelli** [comment]
Yes, it is not a link. But arrows are. What did you expected?

**Comment by flbulgarelli** [comment]
BTW, gobstones/Fundamentos de la programación is the name of the Path.

**Comment by faloi** [comment]
Ok, it was a dumb comment.

However, the _gobstones_ string is a bit redundant, because it's already written next to the guide title.
