### ISSUE TITLE
Inconsistencias en el manejo de la indentación

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-platform#243]
_Pareciera_ ser que el Ace de Biblioteca indenta **con dos espacios** mientras que el de Laboratorio lo hace **con cuatro espacios**.

Lo que termina sucediendo es que si yo defino un código por defecto en un ejercicio y luego la estudiante lo sigue trabajando en Laboratorio, termina viéndose así:

![image](https://cloud.githubusercontent.com/assets/1585835/24931219/cc3ea7fc-1f0c-11e7-8db7-568231bff38a.png)
(En el ejemplo, `cantar!` lo definí yo y `comer_lombriz!` un estudiante.)

**Comment by faloi** [comment]
Che, esto resulta realmente molesto y da lugar a un monton

**Comment by faloi** [comment]
Che, esto resulta realmente molesto y da lugar a un montón de confusiones. Si me tiran un centro puedo intentar arreglarlo yo, estoy usando mucho código extra en mis ultimas guías y realmente me representa una dificultad...

**Comment by flbulgarelli** [comment]
Asumamos una identación en 2 espacios; entonces bug está en laboratorio y el problema debe estar por acá: 

* https://github.com/mumuki/mumuki-laboratory/blob/master/app/assets/javascripts/application/ace-editor-builder.js
* https://github.com/mumuki/mumuki-laboratory/blob/master/app/assets/javascripts/application/ace_editor.js

**Comment by flbulgarelli** [comment]
Revisá en particular este método: 

```javascript
setupOptions: function (minLines) {
      this.editor.setOptions({
        maxLines: Infinity,
        showPrintMargin: false,
        selectionStyle: 'text',
        minLines: minLines,
        showGutter: minLines > 1,
        cursorStyle: minLines > 1 ? 'ace' : 'slim',
        highlightActiveLine: minLines > 1,
        wrap: true
      });
      this.editor.setFontSize(17);
    },
```
