### ISSUE TITLE
Asistencia para insertar directivas en la sección de evaluación

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-platform#244]
Me lo imagino similar a la barra de herramientas de Markdown, pero que permita insertar las directivas en el código extra, el código por defecto o las pruebas.

**Comment by flbulgarelli** [comment]
Es es la lista de directivas de uso frecuente: 

## Interpolaciones que usan el comentario del lenguaje
  * solucion: `/*...content...*/`
  * biblioteca: `/*...extra...*/`
  * test: `/*...test...*/`

## Interpolaciones que NO usan el comentario del lenguaje (siempre con comentario estilo C)
  * `previousContent|previousSolution` . Ejemplo: `/*...previousContent...*/`
  * `solution|content[nro]`. Ejemplo:
        * `/*...solution[-1]...*/` (solucion anterior)
        * `/*...solution[2]...*/` (solucion del segundo ejercicio, en base 1)

## Flags (que sí usan el comentario del lenguaje)
  * `/*[IgnoreContentOnQuery]*/` (hace que el contenido no se envie como parte de una query, solo se puede insertar en el extra o el test)
