### ISSUE TITLE
Editor is extremely slow

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-platform#247]
If you use the editor for a few minutes and a few exercise, it gets slow unusable until yo refresh it.

**Comment by faloi** [comment]
No me resulta inusable pero sí me pasa que se vuelve un poco lento.

**Comment by flbulgarelli** [comment]
Fixed in https://github.com/mumuki/mumuki-bibliotheca/commit/8febd5290cdda3f5f164120848bfbfa5642bd6b6
