### ISSUE TITLE
Error 404 inesperado en organizaciones privadas

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-platform#248]
Muchas veces el login redirige a un 404, con una URL del estilo `/assets/193830492981231.js` o `/styles/81273816248263.css`. Luego si se vuelve a ingresar, borrando esa parte de la URL, funciona correctamente.

No sé cómo reproducirlo, pero estimo que tiende a ocurrir en conexiones lentas. Por ahí con el throttling del Chrome se puede simular esta situación.

**Comment by faloi** [comment]
Update: hay veces que ni siquiera volviendo entrar, por ahora lo estoy solucionando desvinculando y volviendo a vincular al/a estudiante. :pensive:

**Comment by flbulgarelli** [comment]
Algunas preguntas que se me ocurren:

* ocurre siempre, en modo incógnito o sólo cuando ya navegaste antes https://mumuki.io?
* le ocurre a cualquier usuario o a usuarios con pocos permisos (por ejemplo, sólo para la organización en cuestión)? ¿Vos pudiste reproducirlo usando tu usuario?
* ocurre para todas las organizaciones privadas o sólo para algunas?


Por otro lado, ¿podrías pasarnos el _network history_ de Chrome o similar que muestre la secuencia de requests durante este proceso? O al menos, ¿podrías fijarte a dónde apunta el paramtro `origin` del botón de login antes de intentar reproducirlo?

**Comment by faloi** [comment]
> * ocurre siempre, en modo incógnito o sólo cuando ya navegaste antes https://mumuki.io?

En general los pibes no usan el modo incógnito, ni entran a central: acceden directamente a la URL de la orga privada.

> * le ocurre a cualquier usuario o a usuarios con pocos permisos (por ejemplo, sólo para la organización en cuestión)? ¿Vos pudiste reproducirlo usando tu usuario?

Nunca me pasó, me inclino a decir que solo ocurre para los usuarios con pocos permisos.

> * ocurre para todas las organizaciones privadas o sólo para algunas?

No sé, solo estoy usando una organización.

> Por otro lado, ¿podrías pasarnos el _network history_ de Chrome o similar que muestre la secuencia de requests durante este proceso? O al menos, ¿podrías fijarte a dónde apunta el paramtro `origin` del botón de login antes de intentar reproducirlo?

Ok, mañana lo intento y comento de nuevo.

**Comment by faloi** [comment]
Lo del `origin` no supe dónde mirarlo, les mandé los logs por mail. :envelope:

**Comment by flbulgarelli** [comment]
This is happening :sob:: office is still publishing a relative link instead of an absolute link to its server, thus causing this issue in new organizations

**Comment by julian-berbel** [comment]
This seems to no longer be happening
