### ISSUE TITLE
Build a different application dedicated to guide authoring?

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-platform#253]
Since nowadays guide authors are _hardcore_ programmers who find value in building a guide as code project, there are potential guide authors - e.g. @fdodino - that don't like that idea, and feel more familiar with WYSIWYG tools like Google Docs. Seems legit for me. 

Also, we have to admit that current CRUD interface for Guides and Exercises is quite rustic. And adding images is a pain - you have to upload them somewhere and then reference them. 

Having that CRUD in the platform adds code that is not executed by the common user - and has thus different execution load.

I think it would be nice to have a separate application, oriented to guide authoring, that instead of be designed around an exercise CRUD, would be a full (WYSIWYG?) featured editor, were you just write guide text, and split it into exercises into a non obtrusive way, by introducing test components that implicitly delimit them. 

 We could explore components like http://textbox.io/ or https://stackedit.io/editor.

Clearly, I don't want by any means to reinvent the wheel. I wouldn't even consider supporting concurrent edition - just save guide and export to git automatically. But WYSIWYG or at least something close to it is an interesting feature, and also being able to easily add images, plus a better continuous flow for adding exercises.  

Exporting to pdf is a separate issue, described here #236

**Comment by flbulgarelli** [comment]
Related to #215

**Comment by faloi** [comment]
This is being addressed in https://github.com/mumuki/mumuki-content-tools
