### ISSUE TITLE
Atajo para desplegar la ventana de emojis

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-platform#253]
Idealmente, debería ser como el desplegable que muestra GitHub al poner `:`, pero también sirve un shortcut que lo abra en el lugar donde está el cursor y no arriba a la derecha.

**Comment by fedescarpa** [comment]
No estoy de acuerdo. Es muy complejo de hacer ahora y no creo que aporte mucho.

Personalmente un desplegable como el de github no me parece intuitivo. Además, si no sabes que palabra contiene tu emoji tampoco lo encontrás y necesitas de una [cheatsheet](https://www.webpagefx.com/tools/emoji-cheat-sheet/) para encontrarlo.

**Comment by faloi** [comment]
Con un shortcut para abrir la ventanita **en el lugar** me conformaba... :pensive:
