### ISSUE TITLE
Classroom does not work behind a firewall

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-platform#26]
<a href="https://github.com/flbulgarelli"><img src="https://avatars.githubusercontent.com/u/677436?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [flbulgarelli](https://github.com/flbulgarelli)**
_Tuesday Mar 22, 2016 at 18:42 GMT_
_Originally opened as https://github.com/mumuki/mumuki-classroom-api/issues/12_

---

**Comment by flbulgarelli** [comment]
Fixed
