### ISSUE TITLE
Allow content to be deleted by editors

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-platform#264]

**Comment by flbulgarelli** [comment]
Implemented in bibliotheca. Now we should decide how to proceed in laboratory. I think there are three options: 

 * do nothing. Deleting the content in its database will be a manual task
 * delete it logically
 * completely delete it from the database. I think it is risky since it implies destroying tons of progress when deleting in-use content, and an editor could perform it by accident.

**Comment by flbulgarelli** [comment]
We have discussed with with @julian-berbel and @luchotc and we prefer to go with the first option: do nothing. 

So @rodri042 , please just finish the bibliotheca-ui part and close this issue

**Comment by Javi** [comment]
Ya esta UI implementada en mumuki/mumuki-bibliotheca#214
