### ISSUE TITLE
Inconsistencias en la forma de nombrar a la biblioteca

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-platform#266]
* En laboratory: Biblioteca.
* En bibliotheca: Código extra.
* En bibliotheca-api: extra.
* En GitHub: extra.rb

Se que es un cambio grande, pero las inconsistencias entre el modelo y la vista terminan provocando que haya varias formas de nombrar la misma cosa, lo cual resulta confuso para los usuarios.

**Comment by flbulgarelli** [comment]
Renombremos `Código Extra` a `Biblioteca` en bibliotheca. Los otros casos no son importantes para el usuario final.

**Comment by flbulgarelli** [comment]
Won't fix.
