### ISSUE TITLE
Error al seleccionar opción de redirección

### ISSUE THREAD

**Issue by lauramangifesta** [mumuki/mumuki-platform#268]
Después de loguearse aparecen las opciones de redirección (central, smartedu, quedarme acá); al elegir cualquiera de ellas salta un error 400 "Bad Request - The plain HTTP request was sent to HTTPS port".
Si se ingresa directamente desde central.mumuki.io o smartedu.mumuki.io no hay problemas.

**Comment by flbulgarelli** [comment]
Corregido. El cambio estará disponible en https://mumuki.io en el próximo deploy.
