### ISSUE TITLE
Misspells in main menu (Spanish)

### ISSUE THREAD

**Issue by matifreyre** [mumuki/mumuki-platform#268]
The descriptions in the Spanish version of the main menu have several misspells:

"Fundamentos de la Programación" box:
Aprendé los *conceptos fundamentos* de la programación de la manera más fácil...

"Paradigma de Objetos" box:
El paradigma de objetos *es el más conocidos*: es la base de lenguajes tan diferentes como *Smallalk* y Java. Acá podés aprender a *trabjar* con objetos, usando dos híperpopulares: Ruby o JavaScript.

**Comment by flbulgarelli** [comment]
Thanks! Resolved.
