### ISSUE TITLE
No se respetan los fines de línea en ejercicios con editor upload

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-platform#273]
![image](https://cloud.githubusercontent.com/assets/1585835/26594420/d6359924-4567-11e7-800a-ea14769bc5c4.png)

Adjunto **una versión anterior** del código que se ve ahí (no tengo la última a mano). En cualquier caso, el código fue escrito en Sublime Text, en una PC con Linux.

[celulares.rb.txt](https://github.com/mumuki/mumuki-platform/files/1039064/celulares.rb.txt)

**Comment by faloi** [comment]
¿Hay novedades sobre esto? Voy a tener que volver a usarlo pronto y si no está funcionando prefiero no hacerlo.

**Comment by flbulgarelli** [comment]
@faloi cuando es pronto?

**Comment by faloi** [comment]
En verdad, cuando estén disponibles los comentarios, porque sin eso igual no puedo corregir por la herramienta. Pero en mi planificación, "pronto" sería la semana próxima.
