### ISSUE TITLE
Feedback suggestions

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-platform#275]
Although the roadmap isn't that clear (this is sort of experimental), there are some baselines:

* This feature, as the whole platform, **doesn't aim to replace the teacher**. It's just another facility to make her work less repetitive, less tedious, more focused on the students.
* For that reason, this feature **will not provide automatic feedback directly to the student**. It will, instead, assist the teacher during the correction task and she will ultimately decide whether to use the suggestion or not.
* Suggestions will be ranked based on criterias that will be defined (and discovered) during the development. **This ranking will occur on a per exercise basis, across all the organizations.** Private organizations will be able to opt-out of the feature, meaning that its teachers' won't be able to use suggestions at all.
* Some guidelines to write generic, respectful, gender-aware and useful messages will be published, and the Mumuki team will reserve the right to remove any message that doesn't comply with them from the suggestions. That message would, however, remain unmodified for the teacher who sent it and the student who received it.

**Comment by faloi** [comment]
@flbulgarelli, @aguspina, @fedescarpa: before I start working on this, I'd like to discuss these points. Please drop a few lines here. :wink:

**Comment by faloi** [comment]
@asanzo, it would be nice to hear your opinion too.

**Comment by faloi** [comment]
Also, @clombardi, you should read this.

**Comment by flbulgarelli** [comment]
I totally agree with this roadmap draft.

**Comment by faloi** [comment]
Moved to https://github.com/mumuki/mumuki-platform/milestone/2.
