### ISSUE TITLE
Use better Facebook profile pictures

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-platform#277]
The quality is pretty bad, I imagine Facebook can provide something better. See comparison below.

|Facebook|GitHub|
|:-:|:-:|:-:|
|![image](https://cloud.githubusercontent.com/assets/1585835/9343022/a69df762-45d5-11e5-9a91-4f65899fb807.png)|![image](https://cloud.githubusercontent.com/assets/1585835/9343032/b8f53754-45d5-11e5-9d38-ba5f919b1b68.png)|

**Comment by flbulgarelli** [comment]
Nice profile pic :stuck_out_tongue: 

Besides that, this is a omniauth issue - the gem we are using for facebook auth. We should check if it supports that.

**Comment by faloi** [comment]
Seems it [does support it](http://stackoverflow.com/a/10935563/1188303).
