### ISSUE TITLE
Exportar guía de ejercicios a PDF

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-platform#278]

**Comment by flbulgarelli** [comment]
Me gusta esta idea, de hecho hay un branch olvidado que la implementaba: https://github.com/mumuki/mumuki-laboratory/tree/feature-book-pdf. 

El problema es que ese desarrollo murió en parte ante la falta de un diseño gráfico, una idea concreta de cómo pasarlo a papel. ¿@faloi nos pasas un diseño mas o menos detallado de cómo mostrar los ejercicios en una hoja?

**Comment by faloi** [comment]
Yo hoy en día lo querría usar solamente en guías con evaluación manual, donde Mumuki hoy solo cumple el mail de "hago la entrega de mi solución". 

Esta idea por ahí también podría extenderse a guías de práctica mumukizadas, donde no abunden los corolarios ni cuestiones que apelen directamente a la interacción con la plataforma.

Para las guías de aprendizaje no lo veo muy útil...

**Comment by flbulgarelli** [comment]
> Esta idea por ahí también podría extenderse a guías de práctica mumukizadas, donde no abunden los corolarios ni cuestiones que apelen directamente a la interacción con la plataforma.
> 
> Para las guías de aprendizaje no lo veo muy útil...

Yo en este caso pensaba imprimir a dos hojas, una con el enunciado y un área para escribir, y otra con el corolario, de forma que tengas que voltear la página para verlo.

**Comment by flbulgarelli** [comment]
En cualquier caso,  un diseño de cómo te lo imaginás vendría bien, porque no termino de imaginarlo.

**Comment by faloi** [comment]
Ok, pero no me imagino nada más loco que una guía de ejercicios tradicional (bah, de la era pre-Mumuki :wink:).

Mi caso de uso es: llegué a la escuela y no hay internet, me exporto la guía, reparto el PDF y doy una clase tradicional.

**Comment by faloi** [comment]
Sin mucho amor, adjunto PDF de cómo yo me imagino esto (y MD de cómo lo hice - nada que no puedan inferir). Obviamente se le podrían agregar y mejorar mil cosas, pero a mí con eso ya me alcanza.

La guía original es https://github.com/MumukiProject/mumuki-guia-haskell-practica-polimorfismo

* [Práctica Polimorfismo - Markdown](https://github.com/mumuki/mumuki-platform/files/1078350/Practica.polimorfismo.txt)
* [Práctica Polimorfismo - PDF](https://github.com/mumuki/mumuki-platform/files/1078349/Practica.polimorfismo.pdf)

**Comment by faloi** [comment]
Sumo un ejemplo de una guía hecha en Google Docs, con un poco más de formato, una carátula y un índice.

[Guía de ejercicios de ejemplo - PDF](https://github.com/mumuki/mumuki-platform/files/1078382/4.Repeticion.condicional.y.recorridos.-.ejercitacion.complementaria.pdf)

**Comment by flbulgarelli** [comment]
¡Gracias! 

Como primer paso, algo "fácil" de hacer es exportar a un sólo markdown, dado que hay varios conversores de markdown a PDF online.

**Comment by faloi** [comment]
Totalmente. Aunque con un pasito extra podrían también renderizar ese markdown con el estilo de Mumuki y que el PDF lo genere el navegador.

**Comment by flbulgarelli** [comment]
Duplicate of https://github.com/mumuki/mumuki-laboratory/issues/236
