### ISSUE TITLE
Popup "cambios sin publicar" al crear una nueva guía

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-platform#279]
Sucede siempre cuando guardas la guía por primera vez.

![image](https://user-images.githubusercontent.com/1585835/27100143-5fbcbffe-507d-11e7-8de7-14134da80139.png)

**Comment by flbulgarelli** [comment]
Agrego algo más (nota al pie): incluso ese mensaje está mal, debería ser "guardar", no "publicar". Me gustaría dejar el término "publicar" para la acción de mostrar el contenido en el laboratorio.

**Comment by fedescarpa** [comment]
fixed in https://github.com/mumuki/mumuki-bibliotheca/commit/24e911a15a524c18256aa71462ff81de50af001f
