### ISSUE TITLE
"Open in atheneum" from solution view

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-platform#28]
_From @asanzo on March 30, 2016 4:5_

Right now when in Classroom I open a guide to see its students' submissions, I see a link "Abrir en atheneum". This link is very useful.
Yet it'd be grat if you could have that link also in the view where I see the student solution for an exercise. A use case I do a lot is: 
Get into a guide to see a student submission -> Look for the student -> Look for the solution -> Watch the solution and realize I forgot a detail about the exercise text -> press back -> press "Abrir en atheneum" -> look for the exercise and click it -> read the text

I'd very much like to have this shortened by getting a link to the exercise itself, and not for the entire guide.

_Copied from original issue: mumuki/mumuki-atheneum#478_

**Comment by faloi** [comment]
This one is **very handy** to me too. 

Perhaps an even better solution could be a button to see the description within Classroom, but providing a link seems easier to implement and good enough.

**Comment by fedescarpa** [comment]
Nowadays there is no way to open a specific exercise from the Classroom. This is because the URL of the exercise is generated with information that only has Atheneum. First we should change that to go directly to an exercise (like we did with the URL of the guide). @aguspina @flbulgarelli, is it possible?

**Comment by faloi** [comment]
Mmm, ok. And what about directly including the description in Classroom? All we need is a Markdown renderer and a button to show/hide it.

**Comment by flbulgarelli** [comment]
We certainly need a URL in atheneum for an exercise given its slug and exercise id or exercise position. 

Many issues depend on that.

**Comment by flbulgarelli** [comment]
Depends on mumuki/mumuki-atheneum#655
