### ISSUE TITLE
Al subir archivo espera extensión ..rb

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-platform#281]
No sé si pasa con todos los lenguajes o solo con Ruby, pero el efecto que termina teniendo es que el explorador filtra los archivos porque su extensión no es `..rb` (con dos puntos).

**Comment by julian-berbel** [comment]
@faloi Encontré la parte que causa que se filtren los archivos, pero el problema no parece ser que esté esperando una extensión con doble punto, sino que está esperando archivos del MIME type text/*

https://github.com/mumuki/mumuki-laboratory/blob/f8ee93695e65053d7e7a3d5e28260759ba35a335/app/views/layouts/exercise_inputs/editors/_upload.html.erb#L3

**Comment by faloi** [comment]
Sí, después me di cuenta que no era ese el problema, pero nunca edité la issue. ¡Groso!
