### ISSUE TITLE
UI para selección de sugerencias

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-platform#282]
Pensando rápidamente con @fedescarpa, se nos ocurrió esto:

![image](https://user-images.githubusercontent.com/1585835/27757186-e416653c-5dfe-11e7-969f-9860af64dff8.png)

Quedaría afuera el/la autor/a de la sugerencia, que no sé si es importante por ahora...

**Comment by fedescarpa** [comment]
Habría que meterle más amor al diseño de la UI, pero para mi es un buen _approach_

**Comment by fedescarpa** [comment]
@flbulgarelli, @aguspina?

**Comment by flbulgarelli** [comment]
> Habría que meterle más amor al diseño de la UI

De acuerdo. No me resulta evidente que se trata de una sugerencia. ¿Que tal imitar la UI de las respuestas automáticas de email? 

Otra cosa que me genera dudas es cuántas opciones mostrar. Quizás me gustaría que muestre inicialmente 3 y tenga un botón _ver más sugerencias_. Tampoco estoy seguro de que mostrar la cantidad de usos previos sea útil en esta pantalla (aunque si me gustaría verlo en el listado de más sugerencias).

**Comment by aguspina** [comment]
Para mi si es útil que muestre los usos previos. Mostraría las primeras 3 con mejor ranking y pondría un ver más para ver el resto.

+1 a utilizar algo parecido a inbox, pero recordemos que inbox y gmail muestran un texto muy corto, estos capaz son textos largos que no entrarían por completo en el estilo de ese botón.

Sin embargo, me gusta un poco la formo en que @faloi muestra las sugerencias en esa imagen, capaz le agregaría un separador del estilo de un HR o algo asi

**Comment by faloi** [comment]
> De acuerdo. No me resulta evidente que se trata de una sugerencia.

¿Y serviría explicitarlo con un mensaje estilo `Mensajes más utilizados para este ejercicio:` o similar?

> Tampoco estoy seguro de que mostrar la cantidad de usos previos sea útil en esta pantalla

A mí me pareció interesante, sobre todo teniendo en cuenta que va a pasar un tiempo hasta que tengamos respuestas significativas y que pueden darse escenarios como el de la foto (32 versus 1 o 2).

> Mostraría las primeras 3 con mejor ranking y pondría un ver más para ver el resto.

Ok.

> +1 a utilizar algo parecido a inbox, pero recordemos que inbox y gmail muestran un texto muy corto, estos capaz son textos largos que no entrarían por completo en el estilo de ese botón.

Exactamente eso pensamos con @fedescarpa, que en el mail las sugerencias suelen ser 4 o 5 palabras y acá muy probablemente van a ser textos más largos.

> Sin embargo, me gusta un poco la formo en que @faloi muestra las sugerencias en esa imagen, capaz le agregaría un separador del estilo de un HR o algo asi

Sí, definitivamente le falta un separador.

**Comment by flbulgarelli** [comment]
> A mí me pareció interesante, sobre todo teniendo en cuenta que va a pasar un tiempo hasta que tengamos respuestas significativas y que pueden darse escenarios como el de la foto (32 versus 1 o 2).

Pero, ¿por qué sería importante eso? ¿Que haya sido usado muchas veces es sinónimo de calidad en la respuesta? ¿Una respuesta que fue usada 32 veces es 16 veces mejor que una que fue usada 2 veces? O en todo caso, ¿cuan importante es la cantidad de veces que más fue usada?

Yo entiendo y acepto que queramos ordenar por uso, pero, ¿por qué exacerbar el _social proof_ mostrando la cantidad de "likes" de las respuestas? A mi me hace ruido. Lo importante no es la popularidad de la respuesta, sino su calidad.

**Comment by flbulgarelli** [comment]
Otra cosa que me hace ruido: supongamos que Juan escribe una respuesta R. Más tarde, el docente se acuerda de esa respuesta, la reutiliza unas 10 veces, y a la 11va quiere usar nuevamente, pero personalizandola; llamémosla R'.

Juan entonces utiliza R' 5 veces. María luego ve R (que al fin y al cabo tenía mas votos), le gusta y decide reutilizarla, pero mejorando la redacción, generando R''.  Más tarde, Juan  se da cuenta de que cometió un error, y crea una nueva variante de la respuesta, R''', que corrige el error pero no incorpora las mejoras de María (probablemente porque no se dio siquiera cuenta  de que las hizo).

Entonces, tenemos 4 respuestas, todas parecidas y difíciles de diferenciar a simple vista. Lo que es peor, no hubo un verdadero trabajo colaborativo, ya que las versiones nuevas conflictúan con las viejas, y las que están mejor rankeadas son las peores. 

Esto me hace pensar algunas cosas: 

  1. Nuevamente la métrica de cuantas veces fue usada es de dudosa utilidad, al menos en soledad
  1. ¿No sería quizás más importante contar cuantas personas **diferentes** la usaron?
  1. ¡La fecha es relevante! Una respuesta más nueva podría ser más interesante que una más votada. 
  1. Deberíamos incorporar en algún punto el concepto de versión de la respuesta.

**Comment by faloi** [comment]
Sí a todo, esas mismas inquietudes las plasmé [acá](https://github.com/mumuki/mumuki-classroom-api/issues/106) y nunca las discutimos.

> Juan entonces utiliza R' 5 veces. María luego ve R (que al fin y al cabo tenía mas votos), le gusta y decide reutilizarla, pero mejorando la redacción, generando R''. Más tarde, Juan se da cuenta de que cometió un error, y crea una nueva variante de la respuesta, R''', que corrige el error pero no incorpora las mejoras de María (probablemente porque no se dio siquiera cuenta de que las hizo).

¿Tenés alguna idea de cómo resolverlo? A mí no se me ocurre cómo resolverlo sin consultarle al usuario (o a otro actor, un moderador quizás) si la considera una respuesta diferente. Podría establecerse un cierto umbral -digamos, 70% de diferencias- en el cual la consideramos automáticamente diferente, pero en los casos que realmente son interesantes no creo que sea tan fácil de automatizar.

> Yo entiendo y acepto que queramos ordenar por uso, pero, ¿por qué exacerbar el social proof mostrando la cantidad de "likes" de las respuestas? A mi me hace ruido. Lo importante no es la popularidad de la respuesta, sino su calidad.

Claro, pero entender cómo medir esa calidad es justamente el quid del trabajo que estoy haciendo, no podemos pretender que salga en la primera iteración. El _social proof_ es solo una métrica que resulta sencilla de implementar y la única que tenemos por el momento. Hay varias más que tengo en mente (similaridad de soluciones, analizar el feedback automático, mirar las respuestas anteriores, etc).

**Comment by faloi** [comment]
Al margen de la discusión, que me parece hiper valiosa, creo que toda la funcionalidad debería ser catalogada como experimental, y que quienes quieran usarla deberían manifestarlo explícitamente (es decir, hacerlo _opt-in_).

Me parece que si no lo hacemos así nos vamos a enfrascar en discusiones infinitas y nunca vamos a poder llegar a probar nada...

**Comment by flbulgarelli** [comment]
> Me parece que si no lo hacemos así nos vamos a enfrascar en discusiones infinitas y nunca vamos a poder llegar a probar nada...

De acuerdo. 

> Claro, pero entender cómo medir esa calidad es justamente el quid del trabajo que estoy haciendo, no podemos pretender que salga en la primera iteración. El social proof es solo una métrica que resulta sencilla de implementar y la única que tenemos por el momento. Hay varias más que tengo en mente (similaridad de soluciones, analizar el feedback automático, mirar las respuestas anteriores, etc).

¿Y por qué no ordenar por usos recientes? Es también algo *muy* fácil de implementar, también tienen una componente de popularidad (porque si es usada por muchas personas, se mantendrá arriba), pero está libre del factor de inercia y rápidamente las versiones antiguas quedan olvidadas sin necesitar de un modelo de revisiones ni moderación. De hecho, creo que resuelve todos los problemas que acá planteamos. 

Otra ventaja práctica: si creás una nueva respuesta (no importa si es o no una nueva versión de otra existente) en un modelo basado en "likes", dificilmente te será sugerida, porque, claro, tiene un sólo voto :stuck_out_tongue:. Eso no pasa en un modelo basado en fechas.

**Comment by faloi** [comment]
Me convence más tu propuesta que la mía, pero le veo otro problema. 

Con 3 personas que hayan elegido escribir una respuesta propia, una potencial buena respuesta se ignora aunque haya sido utilizada un montón de veces. ¿Qué tal si sacamos una cuenta donde la cantidad de usos también tenga algo de peso?

**Comment by faloi** [comment]
La discusión de lo experimental sigamosla en esta otra issue: https://github.com/mumuki/mumuki-platform/issues/283

**Comment by flbulgarelli** [comment]
Ok a una probar una combinación!
