### ISSUE TITLE
"Try it" doesn't respond in the Mumuki Editor when I use expectations in Wollok

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-platform#29]
_From @ArielUmansky on March 20, 2016 0:25_

I wasn't able to enter to any "editor" nor "content-editor" repo, so I report the issue here. Let me know if I should move this to another repo.

Here's the expectation:

![5](https://cloud.githubusercontent.com/assets/1649905/13901974/ea8b7dae-ee14-11e5-83b4-f31e5d41b302.png)

Here's the "Try it" not responding :P 

![4](https://cloud.githubusercontent.com/assets/1649905/13901977/fc05cc10-ee14-11e5-806e-1f47eb4d9af4.png)

_Copied from original issue: mumuki/mumuki-atheneum#469_

**Comment by flbulgarelli** [comment]
Fixed in new editor
