### ISSUE TITLE
Mumuki requests to runners should be done by websockets

### ISSUE THREAD

**Issue by aguspina** [mumuki/mumuki-platform#293]
This would improve performance

**Comment by flbulgarelli** [comment]
This is not necessary true - at least, not in a practical way -, and has the problem of mantaining multiple connections alive. 

Moreover, some informal studies we have performed show up that students tend to wait 1.2 to 2 minutes between submissions, and each submission takes normally between 600 and 1200ms, so the saved TCP-establishing connection times - a few milliseconds - are not a big issue. 

Closing
