### ISSUE TITLE
Improve network-error/timed out

### ISSUE THREAD

**Issue by aguspina** [mumuki/mumuki-platform#294]

**Comment by flbulgarelli** [comment]
It should show a nicer error message - perhaps with an animation -, explaining that the server is temporary overloaded and showing a button for retrying in 20 (¿?) seconds. 

@aguspina @cucusita

**Comment by cucusita** [comment]
oki doki  👍

**Comment by fedescarpa** [comment]
fixed in https://github.com/mumuki/mumuki-laboratory/pull/910
