### ISSUE TITLE
Guides endpoint

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-platform#296]
A simple GET is all I need... for now :yum:

**Comment by flbulgarelli** [comment]
It should get all guides, right?

**Comment by aguspina** [comment]
Yeah!

**Comment by aguspina** [comment]
@faloi @flbulgarelli I think we may clean database, there are some useless guides without any language id!

**Comment by flbulgarelli** [comment]
Done - in stg

**Comment by flbulgarelli** [comment]
@aguspina Could you add a small test for this :smile:  ?

**Comment by aguspina** [comment]
Of course

**Comment by aguspina** [comment]
Done!
