### ISSUE TITLE
Nombre al crear classroom con parte duplicada

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-platform#30]
_From @sanuzzi on March 16, 2016 15:33_

Si se crea una classroom cuyo nombre comience con "pdep-utn" (o lo correspondiente a cada materia), produce un nombre con esa parte duplicada en el listado de cursos. Ya van 3 cursos que nos vimos tentados de escribir eso, y luego no se puede cambiar.

Tres primeras alternativas que se me ocurren:
- Que a la izquierda del input esté fijo ese texto, indicando que el nombre va a comenzar así, que sea visible.
- Que en el listado de cursos se diferencie lo que corresponde a la materia, respecto del curso en sí. Quizá dividiendo el nombre en dos. Así evitamos la tentativa de escribir todo junto al crear otro nuevo.
- Que se pueda cambiar el nombre luego de crearlo.

_Copied from original issue: mumuki/mumuki-atheneum#466_

**Comment by flbulgarelli** [comment]
Fixed. Now there is a form with more fields, that automatically generated the slug for you: 

![form](https://cloud.githubusercontent.com/assets/677436/14392248/dae018d8-fd96-11e5-8d10-db0f5c59d53f.png)

Broken slugs are not going to be updated, however. This will apply to new courses only.
