### ISSUE TITLE
Next button for pending exercises

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-platform#301]
When an user reaches the end of  a guide, but she still has pending exercises - that is, exercises she didn't resolved within the given guide - the next button should lead to the first pending exercise. 

It should be rendered with a different color and/or caption.

**Comment by flbulgarelli** [comment]
@faloi Please comment

**Comment by faloi** [comment]
Agree, with _didn't resolved_ meaning one of: no submission / wrong submission / submission with warnings. The guide corollary should not appear either.
