### ISSUE TITLE
JAWS no lee el código escrito en el editor

### ISSUE THREAD

**Issue by lauramangifesta** [mumuki/mumuki-platform#308]
Revisar si el lector Jaws funciona con el texto escrito dentro del editor.

**Comment by flbulgarelli** [comment]
Esto fue probado en Chrome, no?

En Firefox anda? @lauramangifesta

**Comment by julian-berbel** [comment]
Acabo de cotejar y JAWS parece funcionar en chrome también.

Para leer el codigo escrito en el editor tuve que seleccionarlo a mano. No sé si el uso normal sería otro...

**Comment by flbulgarelli** [comment]
@lauramangifesta could yo please recheck?

**Comment by flbulgarelli** [comment]
Fixed in https://github.com/mumuki/mumuki-gobstones-runner/pull/94
