### ISSUE TITLE
Foro para estudiantes

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-platform#312]
Necesitamos un foro que permita a los estudiantes intercambiar preguntas y respuestas, y a los docentes, moderarlo.

**Comment by flbulgarelli** [comment]
@fedescarpa @aguspina @lauramangifesta @Gustrucco @argdaniellarrea @rgonzalezt comenten sus ideas acá por favor.

**Comment by lauramangifesta** [comment]
Pongo como disparador el texto de la propuesta del desarrollo del foro:

> 

> Si bien las Comunidades en Facebook han resultado ser una medida eficaz, planteamos, como propuesta superadora, el desarrollo de un foro. A diferencia de los grupos de facebook, el foro permite una mayor facilidad para asociar una consulta a un ejercicio dado, subir el código intentado, el error que tiene, etc. Es decir, al centralizar las consultas por ejercicio, evita la repetición de las mismas y permite que los estudiantes encuentren solución a sus dudas de manera más rápida. El foro desarrollado también dará la posibilidad de advertir cuando se está realizando una consulta que ya fue resuelta, guiándolo hacia la solución ya publicada.

**Comment by flbulgarelli** [comment]
Duplicate of https://github.com/mumuki/mumuki-laboratory/issues/1035
