### ISSUE TITLE
Los links de edición de ejercicio no están funcionando

### ISSUE THREAD

**Issue by julian-berbel** [mumuki/mumuki-platform#322]
Al pasar a angular 1.6 en bibliotheca parece que se agrega a la ruta un ! que no estamos agregando en laboratory y entonces al ingresar la ruta termina viendose de esta forma:

https://bibliotheca.mumuki.io/#!#%2Fguides%2Fmumukiproject%2Fmumuki-guia-java-prueba%2Fexercises%2F1

https://stackoverflow.com/questions/41226122/url-hash-bang-prefix-instead-of-simple-hash-in-angular-1-6

**Comment by flbulgarelli** [comment]
Lo ideal sería mantener la URL original, sin el `!`

**Comment by Javi** [comment]
Ahh, se ve que en la versión anterior había alguna dependencia que volvía a
incluir Angular pero con una versión anterior a la definida en el bower y
la pisaba. Si, la mejor es borrar el ! como dice en el SO, hoy a la noche
lo hago.

**Comment by flbulgarelli** [comment]
Fixed
