### ISSUE TITLE
Add path name and guide position to slug

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-platform#331]
(This should be addressed after #330 is completed, to avoid duplication like `fundamentos-1-fundamentos-1-primeros-programas`)

The slug should be: `<path-name>-<guide-position>-<guide-name>`

**Comment by faloi** [comment]
@flbulgarelli which is the best way to recalculate all the slugs after this is completed? a rake task to run on each instance, a migration?

**Comment by flbulgarelli** [comment]
Yes. A rake task is ok. Actually @giuliano64 already did that. Look in tasks directory

**Comment by faloi** [comment]
Great, the task is [here](https://github.com/mumuki/mumuki-platform/blob/master/lib/tasks/slugs.rake). Any way to automate the run so we don't forget it when we deploy this?

**Comment by flbulgarelli** [comment]
See my comment in #228
