### ISSUE TITLE
Students layout looks broken

### ISSUE THREAD

**Issue by matifreyre** [mumuki/mumuki-platform#34]
When displaying a guide's list of students, the layouts doesn't feel right to me:
![image](https://cloud.githubusercontent.com/assets/10454118/14285446/f0521058-fb21-11e5-8979-cb66d0d4e74d.png)
It looks like a line of 3 students, followed by a line with only 1, then 3, then 1, then 3... I'd rather make all the lines have 3 students, or not have lines at all and just stick them together in each column.
That was the collapsed view, but it also happens in the detailed one:
![image](https://cloud.githubusercontent.com/assets/10454118/14285597/8717ee0e-fb22-11e5-9d03-ab21f3f1397f.png)

**Comment by flbulgarelli** [comment]
Fixed in collapsed view.
