### ISSUE TITLE
Error loging with facebook and Github

### ISSUE THREAD

**Issue by jpvispo** [mumuki/mumuki-platform#346]

**Comment by flbulgarelli** [comment]
Hi @jpvispo, which error did you get? Did you get that error on mumuki.io or in some other platform?

**Comment by jpvispo** [comment]
In http://es.mumuki.io/auth/failure?message=csrf_detected&strategy=github  precisely . But now its fixed, I found that my router backed to factory configuration, and a filter cookie option, is reactivated, setting this option off, the webpage is catching the cookie and everything is going right.

Thanks and excuse me

**Comment by flbulgarelli** [comment]
NP! Thanks!
