### ISSUE TITLE
Display guide/exercise title and description when shared on Facebook

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-platform#349]

**Comment by flbulgarelli** [comment]
We should also setup the link image. See http://stackoverflow.com/questions/19274463/what-is-link-rel-image-src

**Comment by flbulgarelli** [comment]
I think titles and slugs should be consistent. 

Currently, slugs are `$parent.name - $position. $name`. This means it does not include:

* Language
* Path, when the subject is an exercise. 

My proposal is to add path to exercise slugged title. For example: _Fundamentos de la Programación - Primeros Programas - 1. El Tablero_

And page title should be: _Fundamentos de la Programación - Primeros Programas - 1. El Tablero - Mumuki_  - notice the brand at the end. According [this article](https://moz.com/learn/seo/title-tag) that seems a better approach for us. 

Notice also I am removing the guide position from the exercise page title/slug. 

I would keep it still in the guide slugged name:  _Fundamentos de la Programación - 1. Primeros Programas_

However, another possible option is to completly remove positions from slugs and page titles. @faloi ?

**Comment by flbulgarelli** [comment]
Affter discussion with @faloi , this is the choosen format for exercises: 

`$path.name: $guide.name - $name`

And this is the one for guides:

`$path.name: $guide.name`

**Comment by flbulgarelli** [comment]
For future reference, check this link: https://developers.facebook.com/tools/debug/og/object/
