### ISSUE TITLE
Allow navigation to the details of a single student

### ISSUE THREAD

**Issue by matifreyre** [mumuki/mumuki-platform#35]
Currently, you can only expand the details for all of the students of a given guide.
It is possible to filter the list, but sometimes you may want to have an overview of all of them and then you spot a specific one that you would want to see the details of.
It would be nice to have some way to navigate to the details of any particular student without the need of displaying the details for all of them or having to type something to narrow the list down.
Any of these options would do:
- a separate screen, either modal or normal
- an individual expand/collapse button toggle button

**Comment by faloi** [comment]
Duplicated of #32.

**Comment by matifreyre** [comment]
It's NOT the same, as I explained on #32. Please, re-open.

**Comment by faloi** [comment]
Ok, my bad. Reopening.
