### ISSUE TITLE
Feedback of comments

### ISSUE THREAD

**Issue by estefaniamiguel** [mumuki/mumuki-platform#39]
There is no feedback if a comment has been sent once I click the button

**Comment by flbulgarelli** [comment]
Hi @aguspina the same bug seems to be occurring when following an user: user clicks on follow button, but unless you refres the page, you don't see the result. 

I think it is the same bug, related with angular binding. Are you binding the button state directly to the client model, or to a model that is updated from the server?

**Comment by flbulgarelli** [comment]
Fixed.
