### ISSUE TITLE
The description "preview" doesn't match the real layout once published

### ISSUE THREAD

**Issue by matifreyre** [mumuki/mumuki-platform#4]
This is a part of the description in a guide:
![image](https://cloud.githubusercontent.com/assets/10454118/14112173/04213678-f5a4-11e5-8f41-e592d32673b3.png)

This is what the "preview" promises:
![image](https://cloud.githubusercontent.com/assets/10454118/14112197/1b3f0ee8-f5a4-11e5-97d4-b02dc8935932.png)

This is the real result once the guide is published:
![image](https://cloud.githubusercontent.com/assets/10454118/14112218/36d99b28-f5a4-11e5-85a7-edef855fa041.png)

The same happened with this piece of code:
![image](https://cloud.githubusercontent.com/assets/10454118/14112273/6a2892a4-f5a4-11e5-8a77-00da39a06aa1.png)
Preview:
![image](https://cloud.githubusercontent.com/assets/10454118/14112293/80930b32-f5a4-11e5-8699-c1cc47f44f92.png)
Result:
![image](https://cloud.githubusercontent.com/assets/10454118/14112241/508c9642-f5a4-11e5-9817-53bc2802cb5f.png)

**Comment by matifreyre** [comment]
Both cases can be avoided by adding a blank line:
- Case 1: between rows 17 and 18.
- Case 2: between rows 36 and 37.

**Comment by fedescarpa** [comment]
Yes, we use different libraries to render markdown in editor and atheneum. We are working on it.

Standard markdown use a blank line to separate items, code or sections.

i.e.
1. Example 1
   
   > ``` markdown
   > How
   > are
   > you?
   > ```
   > 
   > How are you?
2. Example 2
   
   > ``` markdown
   > How
   > 
   > are
   > you?
   > ```
   > 
   > How
   > are you?

**Comment by faloi** [comment]
Fixed on the new editor.
