### ISSUE TITLE
Per progress sorting looks weird

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-platform#42]
This is how **Progress** sorting looks for one of my courses:

![image](https://cloud.githubusercontent.com/assets/1585835/14413600/3aaa11aa-ff55-11e5-872a-808528f8fe60.png)

I think it should sort by (not sure which criteria should go first):
- number of exercises tried
- rate of success

**Comment by flbulgarelli** [comment]
@fedescarpa ?

**Comment by fedescarpa** [comment]
Rate of success...

`exercises_success_count / exercises_made_count`

**Comment by faloi** [comment]
I think it's not good enough. Consider this example:
- Pablo: 1/1 - rate 100%
- Karen: 7/10 - rate 70%

Sorting by progress should show that Pablo is doing better than Karen, and
clearly that's not the case: her rate is worse, but at least she TRIED more
than him. Also, she's solved more exercises correctly than him.

To sum up, we have 3 numbers that matter:
- rate of success,
- # of exercises tried,
- # of exercises solved.

We should agree on how to consider them and sort accordingly.

**Comment by flbulgarelli** [comment]
@faloi ok, but what about the following scenario:
- Jose: 1/15 
- Maria: 9/10

María has a better rate and solved more exercises, but she tried less. So sorting by number of exercises tried isn't enough, neither.

**Comment by flbulgarelli** [comment]
@fedescarpa @aguspina @faloi Why not just sorting by number of exercises solved?

Considering that, at a given point, each student in the course is able to do the same amount of exercises, so the real _rate_ is always `number_of_exercises_solved/number_of_unlocked_exercises`

**Comment by fedescarpa** [comment]
I'd like to offer the possibility to have a lot of choices and let the user
choice one of its, including ascending and descending order.

**Comment by faloi** [comment]
> I'd like to offer the possibility to have a lot of choices and let the user choice one of its, including ascending and descending order.

Me too, BUT that's a different discussion. I do want to give our teachers the freedom to sort but without making them feel overwhelmed with too many options.

So, the decision of how the progress sorting works should be ours; obviously thinking of which is the most intuitive definition we can achieve.
