### ISSUE TITLE
Deleting exercise from editor won't delete it on Atheneum

### ISSUE THREAD

**Issue by asanzo** [mumuki/mumuki-platform#44]
What wave? :tongue:

**Comment by flbulgarelli** [comment]
Exercises in Atheneum shouldn't be simply removed - that means we could accidentally remove the progress of all students. Instead we should just unlink them from the guide, which is an open issue: https://github.com/mumuki/mumuki-atheneum/issues/453

In the meanwhile, removal of exercises from atheneum is a manual process you should request to info@mumuki.org.

**Comment by flbulgarelli** [comment]
Bottom line: don't remove exercises from guides unless you really mean it and you now what are you doing :smile: . Rewording it or reordering it is usually a better course of action :wink:
