### ISSUE TITLE
Ensure student name is displayed with capital letters

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-platform#49]
I know, it's a fussy issue coming from a fussy person. 

BUT it really hurts to see this (@fedescarpa will agree):
![screenshot from 2016-04-12 15 58 18](https://cloud.githubusercontent.com/assets/1585835/14471957/6776c318-00c7-11e6-9e6d-513f5628e6d3.png)

PS: it's not difficult to implement, just a mix of `_.words` and `_.capitalize`. :grin:

**Comment by fedescarpa** [comment]
We can do this by CSS, I think it is `text-transform: capitalize` or something like that

**Comment by faloi** [comment]
Mmm, I think storing it properly is better. You don't care how the input
was, you want it to look well always.

(Ok, we have to write a "migration" too, but it's a one-time only task.
However, we can start thinking about a way to automate them.)
