### ISSUE TITLE
[Feature] Allow the student to see his/her own solutions to previous exercises of the same guide

### ISSUE THREAD

**Issue by matifreyre** [mumuki/mumuki-platform#5]
Many guides are incremental and a given solution (function, method, etc.) is needed in later exercises.

Sometimes it's possible that students don't remember their own solutions. This can be as simple as forgetting the order of the parameters or how they named an auxiliary function. Forcing the student to go to the previous exercise to check it and then back to the current can turn annoying.

The same way we can decide to show "Extra code" or not, it could be helpful for them to be able to see their own submitted code of previous exercises.

**Comment by fedescarpa** [comment]
duplicated https://github.com/mumuki/mumuki-atheneum/issues/455
