### ISSUE TITLE
Following students is not persisting

### ISSUE THREAD

**Issue by nicombrana** [mumuki/mumuki-platform#52]
Probably a permissions issue, whenever I refresh the page or open the browser, I don't have the students that I was following. I have to follow them again.

**Comment by flbulgarelli** [comment]
What an awful bug! I have confirmed that - I removed my own permissions, followed a new student, and all my follow ups had gone!

**Comment by aguspina** [comment]
Fixed in https://github.com/mumuki/mumuki-classroom-api/pull/32
