### ISSUE TITLE
Special tags for rendering Gobstones' board on exercise description

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-platform#55]
We're doing a lot of manual job to include a board on an exercise description:
1. Write a proper GBB.
2. Publish the exercise.
3. Submit anything, to visualize the board.
4. Take a screenshot of the board.
5. Upload it to GitHub.
6. Include the link in the description.

This work could be avoided by including some sort of "special tags" that allows the teacher to write something like this:

``` markdown
So, your task is to write a `program` that leaves the board like this:

{- 
  type: 'board'
  data: '
     GBB/1.0
     size 3 3
     cell 0 0 Negro 1
     cell 0 1 Negro 1
     cell 0 2 Negro 1
     cell 1 0 Negro 1
     cell 1 1 Negro 1
     cell 1 2 Negro 1
     cell 2 0 Negro 1
     cell 2 1 Negro 1
     cell 2 2 Negro 1
     head 1 1
  '
-}
```

Then, the board would be generated by Gobstones runner and included in the description.

**Comment by faloi** [comment]
We should discuss how to implement this. @aguspina @flbulgarelli please comment.

**Comment by flbulgarelli** [comment]
See https://github.com/rodri042/test-gs-board/blob/master/index.html


@rodri042 is working on this

**Comment by flbulgarelli** [comment]
Does https://github.com/mumuki/mumuki-laboratory/commit/9f5b89e1c14dddf98d6ab1131a0581f186df57a7 fix this issue? @rodri042

**Comment by afska** [comment]
Yes, now the description can contain tags like
https://github.com/rodri042/test-gs-board/blob/master/index.html#L62

2018-01-02 21:08 GMT-03:00 Franco Leonardo Bulgarelli <
notifications@github.com>:

**Comment by flbulgarelli** [comment]
Awesome!
