### ISSUE TITLE
Open in Atheneum link for exercise

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-platform#56]
When writing an exercise I go a lot to Atheneum to see how it looks, specially when trying with different layouts. It would be great to have a way to quickly open it in Atheneum.

An ["open in new" icon](https://design.google.com/icons/#ic_open_in_new) in the upper bar, next to the exercise name could do the trick.

**Comment by flbulgarelli** [comment]
Depends on mumuki/mumuki-atheneum#655

**Comment by faloi** [comment]
No longer necessary with the new editor.
