### ISSUE TITLE
Alumno aparece 2 veces en classroom

### ISSUE THREAD

**Issue by sanuzzi** [mumuki/mumuki-platform#57]
Me inscribí a mi propio curso (para hacer pruebillas siendo un "alumno"), y en la guía 3 aparezco duplicado.

![image](https://cloud.githubusercontent.com/assets/1631264/14578367/d7295080-035c-11e6-836f-d1db83fc49fc.png)

Hasta ahora no vi otros duplicados, pero si hay uno, podría suceder que haya más después.

**Comment by flbulgarelli** [comment]
Fixed. 

@sanuzzi please check now.
