### ISSUE TITLE
Date on submission has a 12-hour format

### ISSUE THREAD

**Issue by gcrespi** [mumuki/mumuki-platform#63]
I.e: when the submission's hour should be 14:22, instead 02:22 is shown.

![captura de pantalla de 2016-04-19 14 38 15](https://cloud.githubusercontent.com/assets/10291211/14653689/89b18272-0650-11e6-8f7d-50dea08aad2e.png)
![captura de pantalla de 2016-04-19 14 38 23](https://cloud.githubusercontent.com/assets/10291211/14653690/89d64670-0650-11e6-9df0-8919a10424fd.png)

(Both submissions in the same day, on the 16th the hour displayed is 11:00 meanwhile on the next one it is 02:22 (14:22)).

**Comment by flbulgarelli** [comment]
Done.The 12-hours format has being kept, but an AM/PM indicator was added.
