### ISSUE TITLE
Add authors info to guide

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-platform#70]
Everyone who contributed in a guide deserves to be mentioned. I can think of 3 ways of contributing:
- as an **author**: a person who was involved in the design of the guide, not necessarily a Mumuki user;
- as a **collaborator**: a Mumuki user that edited something using the Editor, this one should be automatically generated;
- as a **source of inspiration**: someone who wrote something, perhaps outside Mumuki, that was used by the author/s to create the guide.

All these information should be stored in Bibliotheca and a shown on Atheneum.

**Comment by flbulgarelli** [comment]
I think issue 2. has already being addressed - now the editor sets the user who made the change as the commit user. 

Issues 1 and 3 can be addressed using the new `teacher_info` field in guides and exercises, can't it?

Is this enough @faloi ?

**Comment by faloi** [comment]
Mmm, I don't think it's enough, I'd like to show this in Atheneum and we
have no way to extract this from teacher_info field.

For #1, I imagine a list of users that could be filled with either users of
Mumuki or arbitrary names. For #3, a free textbox should be better, so you
can write things like "Some examples were taken from the book XXX by YYY".

**Comment by flbulgarelli** [comment]
In that case, this is more like an atheneum issue that a teacher tools issue, right? What you care about here is to mention possible authors and contributors - for attribution and legal reasons? - so that students can see them, right?

**Comment by faloi** [comment]
Exactly. But you have to input that data, so the issue should be addressed
in both sides.

**Comment by flbulgarelli** [comment]
@fedescarpa added the authors information field to editor today.
