### ISSUE TITLE
Cloning guide repos in Windows fails due to invalid characters

### ISSUE THREAD

**Issue by matifreyre** [mumuki/mumuki-platform#72]
I tried to clone [this guide](https://github.com/pdep-utn/mumuki-TP-funcional-entrega2-sabadoman) from Windows and it's not possible due to the path of one of the exercises (number 3), which includes special characters.

I didn't try this under Linux, but Github and Atheneum support these characters perfectly, it seems. I imagine other OSs support them too. It would be good to do something about it so that we can clone the repo no matter what OS we use. Two options I'm thinking about are:
1. (easier option) do not allow the use of special characters in titles at all.
2. (better option) allow characters, but don't map them directly to directory names. Remove special characters to name the directories and add some metadata within the directory to save the complete title.

Of course, when I say "easier option" that' s what I imagine it to be. I have no idea how much effort it requires :stuck_out_tongue_winking_eye:

**Comment by flbulgarelli** [comment]
Which Windows version are you using?

Everything is encoded - or should at least - be encoded in UTF8. All modern OS should support it.

**Comment by matifreyre** [comment]
Windows 10 Pro

**Comment by matifreyre** [comment]
If you try to create the directory manually in Windows, you get the following message:
![image](https://cloud.githubusercontent.com/assets/10454118/15151753/ec1b696a-16a8-11e6-8e9f-785b242f50a8.png)

**Comment by flbulgarelli** [comment]
Hm, ok, now I get the issue.

**Comment by flbulgarelli** [comment]
Perhaps we could use some kid of escape for those characters, or add an extra "name" property on the exercise or guide metadata, that when present, takes precedence over the directory name.
