### ISSUE TITLE
Changing exam start_time does not work

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-platform#85]
If i change start_time of exam, classroom get's updated, but not in atheneum. 

I tried changing from 24 May to 23 May - today.

**Comment by flbulgarelli** [comment]
@aguspina might this issue have being solved with https://github.com/mumuki/mumuki-atheneum/commit/45d1ba92756a64cc8b08bc13041ca7dc3b972faa ?

**Comment by flbulgarelli** [comment]
@aguspina @fedescarpa could you look at my previous comment, please?

**Comment by aguspina** [comment]
Yes i think so, i think there is a test for that

**Comment by flbulgarelli** [comment]
Ok. Closing
