### ISSUE TITLE
SEO friendly routes

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-platform#87]
Make exercise and guides URIs SEO-friendly.

**Comment by flbulgarelli** [comment]
We could use https://github.com/norman/friendly_id

**Comment by faloi** [comment]
For guides included in a path, it would be nice to make an id following the pattern `/:path_name/:guide_position_in_path`, e.g. `/funcional/1`. And for other guides I'd leave the current id.

For exercises I'd use the `:name-:slug` pattern.

**Comment by giuliano64** [comment]
ok thanks :)

**Comment by faloi** [comment]
We forgot multi-language paths like OOP and functional. 

For thoses cases, I'd add the language to the path, like `/objetos/ruby/1` and `/objetos/javascript/1`

**Comment by flbulgarelli** [comment]
This is not necessary, since the path already has the language name as part of it.
