### ISSUE TITLE
Breadcrumb is lost after refreshing exercise view

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-platform#90]
See screenshot, the guide is lost:

![image](https://cloud.githubusercontent.com/assets/1585835/15696134/1b0451ec-2784-11e6-8b00-d3c1ac6fe5e0.png)

This happens after you hit F5.

**Comment by flbulgarelli** [comment]
Is this still happening @fedescarpa @aguspina ?

**Comment by faloi** [comment]
Happened to me yesterday.

**Comment by flbulgarelli** [comment]
@faloi yes, but @fedescarpa and @aguspina  solved during yesterday's evening  a similar issue. 

I am not being able to reproduce it now. Can you?

**Comment by faloi** [comment]
Nope, seems fixed.
