### ISSUE TITLE
The editor doesn't display the latests guide changes

### ISSUE THREAD

**Issue by mmatos** [mumuki/mumuki-platform#97]
I went in to fix a typo in http://pdep-utn.mumuki.io/exercises/2506-programacion-logica-negacion-y-cuantificacion-haciendo-dedo and the editor is not showing the latest statement and code for it which is current in the github repo, it shows **todo** instead.

I had just logged in, but I think it might be related to some old session information. When I went into the guide it showed an \* in the guide title, as if it had been modified.

**Comment by mmatos** [comment]
BTW, deleting cookies from mumuki didn't solve it, but opening a private window did

**Comment by flbulgarelli** [comment]
@mmatos this is a bug. 

However, as a workaround, you could delete you **local storage**. Deleting cookies will not work since editor doesn't use them.
