### ISSUE TITLE
Be able to easily re-submit solutions sent to central by error

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-platform#99]
Sometimes students don't send solutions to the proper organization, which means not entering in the classroom. 

We need an easy way for admins to, given an student and an organization, to push them back in the proper classroom.

**Comment by flbulgarelli** [comment]
@fedescarpa @aguspina was this issue solved with your latest changes about resubmissions? 

You have exposed an HTTP API call that resubmits solutions, right?

**Comment by aguspina** [comment]
Yup!

**Comment by flbulgarelli** [comment]
Closing.
